// GENERATED by scripts/generate-astra-builder-server-catalog.mjs. Do not edit by hand.
const ASTRA_BUILDER_ENCODING_V1 = "u16le-v1";
const ASTRA_BUILDER_ENCODING_V2 = "u32le-v2";
const ASTRA_BUILDER_CATALOG_VERSION = 2;
const ASTRA_BUILDER_CATALOG_HASH = "94997dfd";
const ASTRA_BUILDER_CATALOG_SIGNATURE = [
  {
    "id": 1,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 2,
    "partId": "foundation_floor",
    "legacyBlockType": 2,
    "rotationSteps": 1
  },
  {
    "id": 3,
    "partId": "nebula_glass",
    "legacyBlockType": 3,
    "rotationSteps": 1
  },
  {
    "id": 4,
    "partId": "star_light",
    "legacyBlockType": 4,
    "rotationSteps": 1
  },
  {
    "id": 5,
    "partId": "stair_straight",
    "legacyBlockType": 5,
    "rotationSteps": 4
  },
  {
    "id": 6,
    "partId": "support_pillar",
    "legacyBlockType": 6,
    "rotationSteps": 1
  },
  {
    "id": 7,
    "partId": "lumen_wood_door",
    "legacyBlockType": 7,
    "rotationSteps": 4
  },
  {
    "id": 8,
    "partId": "lumen_wall_panel",
    "legacyBlockType": 8,
    "rotationSteps": 1
  },
  {
    "id": 9,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 10,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 11,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 12,
    "partId": "foundation_floor",
    "legacyBlockType": 2,
    "rotationSteps": 1
  },
  {
    "id": 13,
    "partId": "foundation_floor",
    "legacyBlockType": 2,
    "rotationSteps": 1
  },
  {
    "id": 14,
    "partId": "foundation_floor",
    "legacyBlockType": 2,
    "rotationSteps": 1
  },
  {
    "id": 15,
    "partId": "foundation_floor",
    "legacyBlockType": 2,
    "rotationSteps": 1
  },
  {
    "id": 16,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 17,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 18,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 19,
    "partId": "lumen_wall",
    "legacyBlockType": 1,
    "rotationSteps": 1
  },
  {
    "id": 20,
    "partId": "stair_straight",
    "legacyBlockType": 5,
    "rotationSteps": 4
  },
  {
    "id": 21,
    "partId": "support_pillar",
    "legacyBlockType": 6,
    "rotationSteps": 1
  },
  {
    "id": 22,
    "partId": "nebula_glass",
    "legacyBlockType": 3,
    "rotationSteps": 1
  },
  {
    "id": 23,
    "partId": "nebula_glass",
    "legacyBlockType": 3,
    "rotationSteps": 1
  },
  {
    "id": 24,
    "partId": "star_light",
    "legacyBlockType": 4,
    "rotationSteps": 1
  },
  {
    "id": 25,
    "partId": "star_light",
    "legacyBlockType": 4,
    "rotationSteps": 1
  },
  {
    "id": 26,
    "partId": "star_light",
    "legacyBlockType": 4,
    "rotationSteps": 1
  },
  {
    "id": 27,
    "partId": "star_light",
    "legacyBlockType": 4,
    "rotationSteps": 1
  },
  {
    "id": 28,
    "partId": "light_bar",
    "legacyBlockType": 9,
    "rotationSteps": 4
  },
  {
    "id": 29,
    "partId": "light_bar",
    "legacyBlockType": 9,
    "rotationSteps": 4
  },
  {
    "id": 30,
    "partId": "light_bar",
    "legacyBlockType": 9,
    "rotationSteps": 4
  },
  {
    "id": 31,
    "partId": "light_bar",
    "legacyBlockType": 9,
    "rotationSteps": 4
  },
  {
    "id": 32,
    "partId": "light_bar",
    "legacyBlockType": 9,
    "rotationSteps": 4
  }
];
const ASTRA_BUILDER_RECIPE_TRAITS = new Map(ASTRA_BUILDER_CATALOG_SIGNATURE.map(({ id, legacyBlockType, rotationSteps }) => [id, { legacyBlockType, rotationSteps }]));
const ASTRA_BUILDER_ALLOWED_RECIPE_IDS = new Set(ASTRA_BUILDER_RECIPE_TRAITS.keys());
module.exports = { ASTRA_BUILDER_CATALOG_VERSION, ASTRA_BUILDER_CATALOG_HASH, ASTRA_BUILDER_CATALOG_SIGNATURE, ASTRA_BUILDER_ENCODING_V1, ASTRA_BUILDER_ENCODING_V2, ASTRA_BUILDER_RECIPE_TRAITS, ASTRA_BUILDER_ALLOWED_RECIPE_IDS };
