/**
 * LUMI Algorithm Constellation — Problem Solving Pattern Registry
 *
 * Invariant: Problem-solving patterns (e.g. temp-swap, preserve-before-overwrite)
 * are algorithm strategies, distinct from Python syntax/builtins.
 */

export const PROBLEM_SOLVING_PATTERN_REGISTRY = Object.freeze({
  'pattern:procedure-decomposition': {
    conceptId: 'pattern:procedure-decomposition',
    patternId: 'pattern:procedure-decomposition',
    displayName: '절차 분해와 단계 조립 (Step 분해)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-EXP-STEP-03',
    why: '복잡한 전체 행동을 작은 단위 명령들로 나누고, 앞 단계의 결과가 다음 단계의 출발 상태가 되도록 올바른 순서로 조립해요.',
    tinyExample: 'energy = energy + charge\nenergy = energy * boost\nenergy = energy - shield',
    syntaxExample: '# 1단계: 충전 -> 2단계: 증폭 -> 3단계: 소모',
    predictionCheck: {
      prompt: '충전 후 증폭하는 것과 증폭 후 충전하는 것은 결과가 같을까요, 다를까요?',
      options: ['서로 다르다', '항상 같다'],
      expected: '서로 다르다',
    },
    protocolRepairId: 'PR-DECOMPOSE-001',
  },
  'pattern:preserve-before-overwrite': {
    conceptId: 'pattern:preserve-before-overwrite',
    patternId: 'pattern:preserve-before-overwrite',
    displayName: '소실 전 백업 전략 (temp 패턴)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-EXP-SWAP-04',
    why: '변수의 값을 덮어쓰면 원래 정보가 사라지므로, 덮어쓰기 전에 임시 상자(temp)에 안전하게 백업해 두는 생각의 전략이에요.',
    tinyExample: 'temp = box_a  # box_a를 잃어버리기 전에 백업!\nbox_a = box_b\nbox_b = temp',
    syntaxExample: 'temp = box_a\nbox_a = box_b\nbox_b = temp',
    predictionCheck: {
      prompt: 'temp = box_a; box_a = box_b 실행 후 box_b에 box_a의 원래 값을 넣으려면 무엇을 대입해야 할까요?',
      options: ['temp', 'box_a', 'box_b', 'None'],
      expected: 'temp',
    },
    protocolRepairId: 'PR-TEMP-SWAP-001',
  },
  'pattern:counterexample-search': {
    conceptId: 'pattern:counterexample-search',
    patternId: 'pattern:counterexample-search',
    displayName: '작은 반례로 항상인지 확인하기',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-EXP-EQUIV-09',
    why: '몇 번 맞는 것만으로 항상 같다고 할 수 없어요. 서로 달라지는 작은 입력 하나를 찾으면 항상 같다는 주장을 검증할 수 있어요.',
    tinyExample: '(x + 1) * 2와 x + 2는 x=0에서는 둘 다 2로 같지만 x=1에서는 4와 3으로 달라요.',
    syntaxExample: '# 작은 값 0, 1, 경계값을 차례로 비교',
    predictionCheck: {
      prompt: '두 식이 항상 같다는 주장을 깨뜨리는 가장 확실한 증거는 무엇일까요?',
      options: ['서로 다른 결과가 나오는 입력(반례) 하나', '같은 결과가 나오는 입력 하나'],
      expected: '서로 다른 결과가 나오는 입력(반례) 하나',
    },
    protocolRepairId: 'PR-COUNTEREXAMPLE-001',
  },
  'pattern:upper-clamp': {
    conceptId: 'pattern:upper-clamp',
    patternId: 'pattern:upper-clamp',
    displayName: '상한 제한 (Upper Clamp)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-COND-CLAMP-16',
    why: '값이 안전 한도를 넘었을 때 버리지 않고, 정상 값은 그대로 보존하며 한도를 초과한 값만 최대 허용치로 되돌리는 생각의 전략이에요.',
    tinyExample: 'if value > limit:\n    value = limit',
    syntaxExample: 'if requested > max_power:\n    return max_power\nreturn requested',
    predictionCheck: {
      prompt: '최대 허용치가 100일 때, 120이 요청되면 어떤 값으로 되돌려야 할까요?',
      options: ['100', '120', '0', '20'],
      expected: '100',
    },
    protocolRepairId: 'PR-UPPER-CLAMP-001',
  },
  'pattern:filter-accumulate': {
    conceptId: 'pattern:filter-accumulate',
    patternId: 'pattern:filter-accumulate',
    displayName: '조건 선별과 누적 (Filter & Accumulate)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SEQ-005',
    why: '모든 항목을 순회하되, 조건을 통과한 항목만 정해진 측정값(값 자체 또는 1)으로 상태 변수에 누적해요.',
    tinyExample: 'total = 0\nfor x in items:\n    if x > 0:\n        total = total + x',
    syntaxExample: 'total = 0\nfor x in items:\n    if condition(x):\n        total = total + value',
    predictionCheck: {
      prompt: '조건을 만족하는 항목만 더하거나 셀 때, 조건을 만족하지 않는 항목을 만나면 어떻게 해야 할까요?',
      options: ['상태를 바꾸지 않고 다음 항목으로 넘어간다', '전체 계산을 0으로 초기화한다'],
      expected: '상태를 바꾸지 않고 다음 항목으로 넘어간다',
    },
    protocolRepairId: 'PR-FILTER-ACCUM-001',
  },
  'pattern:first-item-initialization': {
    conceptId: 'pattern:first-item-initialization',
    patternId: 'pattern:first-item-initialization',
    displayName: '첫 항목 기준 초기화 (First Item Init)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SEQ-MINMAX-32',
    why: '임의의 숫자나 0으로 시작하면 데이터 범위에 따라 잘못된 최솟값·최댓값이 될 수 있으므로, 비어 있지 않은 리스트의 첫 항목을 유효한 초기 기준값으로 삼아요.',
    tinyExample: 'smallest = items[0]\nlargest = items[0]\nfor x in items:\n    if x < smallest:\n        smallest = x\n    if x > largest:\n        largest = x',
    syntaxExample: 'base = items[0]\nfor item in items:\n    # base와 비교하며 상태 갱신',
    predictionCheck: {
      prompt: '모두 음수인 리스트 [-5, -9, -2]의 최댓값을 찾을 때, 초기값을 0으로 시작하면 어떤 문제가 생길까요?',
      options: ['입력에 없는 0을 최댓값이라고 잘못 판단하게 된다', '아무 문제없이 -2를 찾는다'],
      expected: '입력에 없는 0을 최댓값이라고 잘못 판단하게 된다',
    },
    protocolRepairId: 'PR-FIRST-ITEM-INIT-001',
  },
  'pattern:running-prefix-state': {
    conceptId: 'pattern:running-prefix-state',
    patternId: 'pattern:running-prefix-state',
    displayName: '지나온 상태를 매 순간 기록하기 (Running Prefix State)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SEQ-RUNNING-35',
    why: '순회가 끝난 뒤의 최종 결과 하나만 구하는 것이 아니라, 각 단계를 거칠 때마다 변화하는 중간 상태를 결과 목록에 차례로 기록해요.',
    tinyExample: 'journal = []\ntotal = 0\nfor delta in changes:\n    total = total + delta\n    journal.append(total)',
    syntaxExample: 'result = []\nstate = 0\nfor x in items:\n    state = state + x\n    result.append(state)',
    predictionCheck: {
      prompt: '입력 [3, -1, 4]에서 3, -1을 차례로 더했을 때 두 번째 시점의 누적 기록은 얼마일까요?',
      options: ['2', '3', '6', '-1'],
      expected: '2',
    },
    protocolRepairId: 'PR-RUNNING-PREFIX-001',
  },
  'pattern:boundary-wraparound': {
    conceptId: 'pattern:boundary-wraparound',
    patternId: 'pattern:boundary-wraparound',
    displayName: '경계 항목을 반대편으로 보내기 (Boundary Wraparound)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SEQ-ROTATE-38',
    why: '순환 구조에서 한쪽 끝에 있는 경계 항목을 따로 분리해 반대편 끝으로 보내고, 나머지 항목들의 상대적 순서는 그대로 유지해요.',
    tinyExample: '# 마지막 항목을 맨 앞으로 이동\nrotated = [items[-1]]\nfor item in items[:-1]:\n    rotated.append(item)',
    syntaxExample: 'rotated = [items[-1]]\nfor item in items[:-1]:\n    rotated.append(item)',
    predictionCheck: {
      prompt: '[1, 2, 3, 4]를 오른쪽으로 한 칸 회전시켰을 때 맨 앞으로 이동하는 항목은 무엇일까요?',
      options: ['4 (마지막 항목)', '1 (첫 번째 항목)', '3', '2'],
      expected: '4 (마지막 항목)',
    },
    protocolRepairId: 'PR-BOUNDARY-WRAP-001',
  },
  'pattern:run-boundary-flush': {
    conceptId: 'pattern:run-boundary-flush',
    patternId: 'pattern:run-boundary-flush',
    displayName: '바뀌는 경계에서 묶음 기록하기 (Run Boundary Flush)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-STR-COMPRESS-39',
    why: '같은 값이 이어지는 동안 횟수를 늘리다가, 값이 바뀌는 순간 지금까지의 묶음을 결과에 기록하고 새 값과 횟수 1로 다시 시작해요. 반복이 끝난 뒤 마지막 묶음도 잊지 않고 기록해요.',
    tinyExample: 'A, A 다음에 B가 도착하면 → [A, 2]를 기록하고 → [B, 1] 새 묶음을 시작해요.',
    syntaxExample: '# 같은 값이면 횟수 증가\n# 값이 바뀌면 이전 묶음 기록 → 새 묶음 시작\n# 탐색이 끝나면 마지막 묶음 기록',
    predictionCheck: {
      prompt: '문자열 "AABA"에서 첫 번째 A 묶음과 마지막 A는 어떻게 다루어야 할까요?',
      options: [
        'B로 끊어져 있으므로 각각 [A, 2]와 [A, 1]의 별개 묶음으로 기록한다',
        '같은 문자이므로 하나의 [A, 3]으로 합친다',
      ],
      expected: 'B로 끊어져 있으므로 각각 [A, 2]와 [A, 1]의 별개 묶음으로 기록한다',
    },
    protocolRepairId: 'PR-RUN-BOUNDARY-FLUSH-001',
  },
  'pattern:sliding-window-scan': {
    conceptId: 'pattern:sliding-window-scan',
    patternId: 'pattern:sliding-window-scan',
    displayName: '같은 크기 검사 창을 한 칸씩 옮기기 (Sliding Window Scan)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-STR-PATTERN-40',
    why: '새 항목이 들어올 때마다 검사 목록에 추가하고 목표 패턴과 같은지 비교한 뒤, 다음 검사를 위해 최근 항목들만 남겨서 겹치는 패턴도 놓치지 않고 탐색해요.',
    tinyExample: 'IOIOI를 길이 3의 창으로 보면 → IOI(일치), OIO(불일치), IOI(일치)예요.',
    syntaxExample: '# 새 항목을 검사 목록에 추가\n# 목표 모양과 비교\n# 다음 겹침 검사를 위해 필요한 최근 항목만 보존',
    predictionCheck: {
      prompt: '문자열 "IOIOI"에서 0번 위치의 "IOI"를 찾은 뒤 검사 목록을 완전히 비우지 않고 최근 2글자("OI")를 남기는 이유는 무엇일까요?',
      options: [
        '겹쳐서 시작하는 두 번째 "IOI"(2번 위치)를 놓치지 않고 찾기 위해',
        '문자열 길이를 늘리기 위해',
      ],
      expected: '겹쳐서 시작하는 두 번째 "IOI"(2번 위치)를 놓치지 않고 찾기 위해',
    },
    protocolRepairId: 'PR-SLIDING-WINDOW-SCAN-001',
  },
  'pattern:deduplicate-then-measure': {
    conceptId: 'pattern:deduplicate-then-measure',
    patternId: 'pattern:deduplicate-then-measure',
    displayName: '겹친 항목을 하나로 모은 뒤 재기 (Deduplicate then Measure)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SET-UNIQUE-01',
    why: '중복된 항목이 많은 목록에서 집합(set)으로 겹친 값을 하나로 합친 뒤 그 크기를 재어 서로 다른 종류 수를 구해요.',
    tinyExample: '[철, 철, 얼음, 철] → {철, 얼음} → 서로 다른 종류 2',
    syntaxExample: '# 목록을 집합으로 변환 → 중복 제거\n# 집합의 크기를 측정하여 종류 수 계산',
    predictionCheck: {
      prompt: '["사과", "바나나", "사과", "사과"]를 집합으로 모으면 고유한 과일 종류는 몇 개가 될까요?',
      options: ['2개 (사과, 바나나)', '4개', '3개', '1개'],
      expected: '2개 (사과, 바나나)',
    },
    protocolRepairId: 'PR-DEDUP-MEASURE-001',
  },
  'pattern:membership-query': {
    conceptId: 'pattern:membership-query',
    patternId: 'pattern:membership-query',
    displayName: '기록 안에 찾는 항목이 있는지 묻기 (Membership Query)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SET-MEMBERSHIP-42',
    why: '특정 항목이 명단이나 집합 안에 이미 등록되어 있는지 확인하여 참(True) 또는 거짓(False)을 결정해요.',
    tinyExample: '루미, 노바가 적힌 명단에 노바가 있는지 확인 → True',
    syntaxExample: '# 집합이나 목록에 대상 항목이 포함되어 있는지 확인',
    predictionCheck: {
      prompt: '승객 명단에 ["루미", "노바"]만 있을 때 "솔"이 탑승했는지 물어보면 결과는 무엇일까요?',
      options: ['False (명단에 없음)', 'True (명단에 있음)'],
      expected: 'False (명단에 없음)',
    },
    protocolRepairId: 'PR-MEMBERSHIP-QUERY-001',
  },
  'pattern:intersection-by-membership': {
    conceptId: 'pattern:intersection-by-membership',
    patternId: 'pattern:intersection-by-membership',
    displayName: '다른 목록에도 있는 항목만 공통 기록에 추가하기 (Intersection by Membership)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-SET-INTERSECT-43',
    why: '첫 번째 목록을 순회하면서 두 번째 목록에도 들어있는 항목만 골라 공통 집합에 담아 중복 없이 공통 항목 수를 구해요.',
    tinyExample: '기지A [A, A, B, C], 기지B [A, C, D] → B에도 있는 A, C만 공통 보관함에 담기 → 공통 종류 2',
    syntaxExample: '# 첫 번째 목록 순회\n# 두 번째 목록에 있으면 공통 집합에 추가\n# 공통 집합의 크기 반환',
    predictionCheck: {
      prompt: '기지A에 [1, 1, 2], 기지B에 [1, 3]이 있을 때 두 기지가 공통으로 가진 서로 다른 부품 수는 몇 개일까요?',
      options: ['1개 (부품 1)', '2개', '3개', '0개'],
      expected: '1개 (부품 1)',
    },
    protocolRepairId: 'PR-INTERSECTION-BY-MEMBERSHIP-001',
  },
  'pattern:frequency-table': {
    conceptId: 'pattern:frequency-table',
    patternId: 'pattern:frequency-table',
    displayName: '항목마다 횟수 칸을 만들어 누적하기 (Frequency Table)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-FREQ-44',
    why: '항목이 등장할 때마다 기록표에 해당 이름표가 있는지 확인하여, 이미 있으면 횟수를 늘리고 처음이면 1에서 시작해요.',
    tinyExample: 'A, B, A 순서로 오면 → A 칸은 2, B 칸은 1',
    syntaxExample: '# 항목 도착 → 이름표 확인\n# 이미 있으면 횟수 1 증가\n# 처음이면 1로 새로 등록',
    predictionCheck: {
      prompt: '신호 [A, B, A, C]에서 A 신호가 두 번째로 등장했을 때 어떤 일이 일어날까요?',
      options: [
        '새로운 칸을 만들지 않고 기존 A 칸의 숫자를 1에서 2로 올린다',
        '새로운 A 칸을 하나 더 추가한다',
        '모든 칸의 숫자를 1로 초기화한다',
      ],
      expected: '새로운 칸을 만들지 않고 기존 A 칸의 숫자를 1에서 2로 올린다',
    },
    protocolRepairId: 'PR-FREQ-TABLE-001',
  },
  'pattern:argmax-by-associated-value': {
    conceptId: 'pattern:argmax-by-associated-value',
    patternId: 'pattern:argmax-by-associated-value',
    displayName: '이름표에 연결된 값을 비교해 최댓값의 주인 찾기 (Argmax by Associated Value)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-MODE-45',
    why: '기록표의 횟수나 점수를 비교하면서 지금까지 본 가장 큰 값보다 더 큰 값을 만났을 때만 최댓값의 주인을 교체해요. 동률일 때는 먼저 등장한 주인이 유지돼요.',
    tinyExample: 'A가 3회, B가 2회이면 → 가장 많이 나온 항목은 A',
    syntaxExample: '# 첫 항목을 현재 1위로 설정\n# 각 항목의 연결된 값을 비교\n# 더 큰 값을 발견했을 때만 1위 교체',
    predictionCheck: {
      prompt: 'B가 2회, A가 2회 등장하고 B가 먼저 나왔다면, 엄격히 더 큰 값일 때만 교체할 때 최종 1위는 누구일까요?',
      options: [
        '먼저 등장한 B가 유지된다',
        '나중에 등장한 A로 바뀐다',
        '둘 다 탈락한다',
      ],
      expected: '먼저 등장한 B가 유지된다',
    },
    protocolRepairId: 'PR-ARGMAX-VALUE-001',
  },
  'pattern:keyed-state-update': {
    conceptId: 'pattern:keyed-state-update',
    patternId: 'pattern:keyed-state-update',
    displayName: '이름표로 상태를 찾아 누적 갱신하기 (Keyed State Update)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-STOCK-46',
    why: '화물 코드나 팀 이름으로 장부를 찾아 기존 수량에 입고량을 더하고, 요청받은 특정 이름표의 최종 수량을 조회해요.',
    tinyExample: '기존 BOLT 2개에 3개 입고 → BOLT 수량은 5',
    syntaxExample: '# 변경 요청 순회\n# 이름표가 장부에 있으면 기존 수량에 추가 누적\n# 장부에 없으면 새 수량으로 등록\n# 요청한 이름표의 최종 수량 조회',
    predictionCheck: {
      prompt: '장부에 없는 새 부품 "CORE" 4개가 입고되었을 때 장부는 어떻게 변할까요?',
      options: [
        '"CORE" 이름표를 새로 만들고 수량 4를 기록한다',
        '장부에 없는 부품이므로 무시한다',
        '기존 부품들의 수량을 모두 4로 바꾼다',
      ],
      expected: '"CORE" 이름표를 새로 만들고 수량 4를 기록한다',
    },
    protocolRepairId: 'PR-KEYED-UPDATE-001',
  },
  'pattern:complement-search': {
    conceptId: 'pattern:complement-search',
    patternId: 'pattern:complement-search',
    displayName: '목표에서 현재 값을 빼 필요한 짝 찾기 (Complement Search)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-TWOSUM-47',
    why: '두 수의 합을 일일이 모두 더해보지 않고, 목표 합에서 현재 값을 빼 필요한 짝을 먼저 정한 뒤 뒤쪽 목록에 그 값이 있는지 확인해요.',
    tinyExample: '목표 10, 현재 4 → 필요한 짝은 6 → 뒤쪽 목록에서 6 탐색',
    syntaxExample: '# 현재 캡슐 확인\n# 목표 - 현재값으로 필요한 짝 계산\n# 남은 뒤쪽 목록에서 필요한 짝 탐색',
    predictionCheck: {
      prompt: '목표 합이 10이고 현재 캡슐의 에너지가 4일 때, 짝을 이루기 위해 뒤쪽 목록에서 찾아야 하는 에너지는 얼마일까요?',
      options: [
        '6 (10 - 4)',
        '14 (10 + 4)',
        '4',
        '10',
      ],
      expected: '6 (10 - 4)',
    },
    protocolRepairId: 'PR-COMPLEMENT-SEARCH-001',
  },
  'pattern:frequency-signature-comparison': {
    conceptId: 'pattern:frequency-signature-comparison',
    patternId: 'pattern:frequency-signature-comparison',
    displayName: '항목별 횟수표를 지문처럼 비교하기 (Frequency Signature Comparison)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-ANAGRAM-49',
    why: '순서가 달라도 항목의 종류와 각 횟수가 모두 같으면 같은 구성이에요. 두 목록을 각각 빈도표로 바꾼 뒤 표 전체를 비교해요.',
    tinyExample: 'A,B,A 와 B,A,A → 둘 다 A칸 2, B칸 1이라 같은 구성',
    syntaxExample: '# 두 목록을 각각 횟수표로 만들기\n# 표의 종류와 개수가 하나도 빠짐없이 같은지 비교',
    predictionCheck: {
      prompt: 'A,B,A와 B,A,A가 같은 구성이라고 할 수 있는 이유는 무엇일까요?',
      options: [
        'A칸 2, B칸 1로 종류별 횟수가 모두 같기 때문',
        '글자 순서까지 완전히 같기 때문',
      ],
      expected: 'A칸 2, B칸 1로 종류별 횟수가 모두 같기 때문',
    },
    protocolRepairId: 'PR-FREQ-SIGNATURE-001',
  },
  'pattern:first-state-divergence': {
    conceptId: 'pattern:first-state-divergence',
    patternId: 'pattern:first-state-divergence',
    displayName: '기대 상태와 처음 달라진 순간 찾기 (First State Divergence)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-BUG-50',
    why: '최종 결과만 보지 않고 입력을 하나씩 처리한 뒤의 기대 상태와 실제 상태를 비교해요. 처음 달라진 단계의 규칙을 고치면 뒤의 오류가 함께 사라질 수 있어요.',
    tinyExample: 'A 처리 후 기대 A칸 1 / 실제 A칸 0 → 첫 단계에서 이미 어긋남',
    syntaxExample: '# 각 단계의 기대 횟수표와 실제 횟수표를 나란히 비교\n# 처음 어긋난 단계의 규칙부터 고치기',
    predictionCheck: {
      prompt: '버그 코드가 A를 처리한 직후 기대는 A칸 1인데 실제는 A칸 0이었다면, 어느 단계의 규칙을 고쳐야 할까요?',
      options: [
        '처음 등장한 항목의 횟수를 정하는 단계',
        '이미 있는 항목의 횟수를 늘리는 단계',
      ],
      expected: '처음 등장한 항목의 횟수를 정하는 단계',
    },
    protocolRepairId: 'PR-FIRST-DIVERGENCE-001',
  },
  'pattern:remember-then-query': {
    conceptId: 'pattern:remember-then-query',
    patternId: 'pattern:remember-then-query',
    displayName: '지나온 값을 기억하고 필요한 짝 확인하기 (Remember then Query)',
    kind: 'algorithm-pattern',
    canonicalFirstProblemId: 'AC-DICT-ONESHOT-48',
    why: '현재 캡슐과 짝이 되는 값이 지금까지 지나온 기억 보관함에 있는지 먼저 확인하고, 없으면 현재 값을 다음 탐색을 위해 보관함에 기억해요.',
    tinyExample: '현재 7, 필요 2 → 기억함 {3, 8, 2}에 2가 있음 → True',
    syntaxExample: '# 필요한 짝 계산\n# 지금까지 지나온 기억 보관함에서 짝 확인\n# 없으면 현재 값을 기억 보관함에 추가',
    predictionCheck: {
      prompt: '현재 값을 기억 보관함에 넣기 전에 필요한 짝이 보관함에 있는지 먼저 확인하는 이유는 무엇일까요?',
      options: [
        '하나뿐인 현재 캡슐을 자기 자신과 짝지어 두 번 사용하는 오류를 막기 위해',
        '기억 보관함의 크기를 줄이기 위해',
      ],
      expected: '하나뿐인 현재 캡슐을 자기 자신과 짝지어 두 번 사용하는 오류를 막기 위해',
    },
    protocolRepairId: 'PR-REMEMBER-THEN-QUERY-001',
  },
})

export function getPatternDetails(patternId) {
  return PROBLEM_SOLVING_PATTERN_REGISTRY[patternId] || null
}

export function getPatternsNeededForProblem(problemId, thinkingPatterns = {}) {
  const patternIds = [...new Set([
    ...(thinkingPatterns.requires || []),
    ...(thinkingPatterns.introduces || []),
  ])]
  return patternIds.map((id) => PROBLEM_SOLVING_PATTERN_REGISTRY[id]).filter(Boolean)
}
