const BASE_WORLD = Object.freeze({
  width: 6,
  height: 5,
  rover: { x: 2, y: 2, direction: 0, energy: 100, awake: true },
  target: { x: 2, y: 2, kind: 'beacon' },
  obstacles: [],
})

function dataMission({ id, codeName, order, title, objective, briefing, concepts, starterCode, goals, mustUse = [], mustCall = [], hints = [] }) {
  return {
    id,
    codeName,
    actId: 'act-7-data',
    order,
    difficulty: order === 5 ? 'field-test' : 'core',
    title,
    eyebrow: `ACT 7 · DATA CORE · ${order}/5 BETA`,
    objective,
    briefing,
    concepts,
    starterCode,
    memoryFragment: {
      label: '손상된 데이터 신호',
      code: '# 자료의 모양과 필요한 연산을 관찰하세요.\n# 값은 직접 완성해야 합니다.',
      duration: 1800,
      autoPlay: true,
    },
    scaffold: {
      mode: 'edit',
      visibleTools: ['run', 'reset', 'step', 'replay', 'memory', 'mission-tabs', 'hud'],
    },
    world: BASE_WORLD,
    goals,
    conceptEvidence: { mustUse, mustCall },
    hints,
    rewardPolicy: 'standard-crystals',
  }
}

export const LUMI_DATA_CORE_MISSIONS = [
  dataMission({
    id: 'lumi-data-7-01', codeName: '7-1', order: 1,
    title: '신호 목록 만들기',
    objective: '세 개의 구조 신호를 list에 저장하고 개수를 출력하세요.',
    briefing: '여러 값을 순서대로 보관하는 첫 데이터 컨테이너를 복구합니다.',
    concepts: ['list', 'len'],
    starterCode: 'signals = []\n\n# ALPHA, BETA, GAMMA를 리스트에 저장하세요.\nprint(len(signals))',
    goals: [{ type: 'stdoutIncludes', value: '3' }],
    mustUse: ['list'], mustCall: ['len', 'print'],
    hints: ['대괄호 안에 문자열 세 개를 쉼표로 구분합니다.', '`signals = ["ALPHA", "BETA", "GAMMA"]` 형태를 사용합니다.'],
  }),
  dataMission({
    id: 'lumi-data-7-02', codeName: '7-2', order: 2,
    title: '패킷 분리 split',
    objective: '구분자 | 로 연결된 패킷을 세 신호로 분리하세요.',
    briefing: '관제소에서 한 줄로 도착한 문자열을 리스트로 해독합니다.',
    concepts: ['문자열', 'split', 'list'],
    starterCode: 'packet = "ALPHA|BETA|GAMMA"\nsignals = []\n\n# packet을 | 기준으로 나누세요.\nprint(len(signals))',
    goals: [{ type: 'stdoutIncludes', value: '3' }],
    mustCall: ['split', 'len', 'print'],
    hints: ['문자열의 `.split("|")`은 나뉜 문자열 리스트를 반환합니다.'],
  }),
  dataMission({
    id: 'lumi-data-7-03', codeName: '7-3', order: 3,
    title: '신호 재조립 join',
    objective: '리스트의 신호를 - 로 연결해 하나의 송신 문자열을 만드세요.',
    briefing: '나뉜 데이터 조각을 관제소가 읽을 수 있는 패킷으로 다시 조립합니다.',
    concepts: ['list', 'join', '문자열'],
    starterCode: 'signals = ["ALPHA", "BETA", "GAMMA"]\nmessage = ""\n\n# - 구분자로 signals를 연결하세요.\nprint(message)',
    goals: [{ type: 'stdoutIncludes', value: 'ALPHA-BETA-GAMMA' }],
    mustUse: ['list'], mustCall: ['join', 'print'],
    hints: ['구분자 문자열에서 `"-".join(signals)`를 호출합니다.'],
  }),
  dataMission({
    id: 'lumi-data-7-04', codeName: '7-4', order: 4,
    title: '변하지 않는 좌표 tuple',
    objective: '목표 좌표 (4, 2)를 tuple로 저장하고 출력하세요.',
    briefing: '한 쌍으로 묶여 변경되지 않아야 하는 좌표 데이터를 복구합니다.',
    concepts: ['tuple', '좌표'],
    starterCode: 'target = ()\n\n# x=4, y=2 좌표를 튜플로 저장하세요.\nprint(target)',
    goals: [{ type: 'stdoutIncludes', value: '(4, 2)' }],
    mustUse: ['tuple'], mustCall: ['print'],
    hints: ['튜플은 `(4, 2)`처럼 소괄호와 쉼표로 만듭니다.'],
  }),
  dataMission({
    id: 'lumi-data-7-05', codeName: '7-F', order: 5,
    title: '상태 사전 dict',
    objective: '루미의 name과 energy를 dictionary에 저장하고 80을 출력하세요.',
    briefing: '이름표가 붙은 여러 상태를 하나의 데이터 코어에 통합합니다.',
    concepts: ['dict', 'key', 'value'],
    starterCode: 'status = {}\n\n# name은 LUMI, energy는 80으로 저장하세요.\nprint(status.get("energy", 0))',
    goals: [{ type: 'stdoutIncludes', value: '80' }],
    mustUse: ['dict'], mustCall: ['get', 'print'],
    hints: ['사전은 `{"name": "LUMI", "energy": 80}`처럼 key와 value를 콜론으로 연결합니다.'],
  }),
]

export const LUMI_DATA_CORE_SET = Object.freeze({
  id: 'lumi-act-7-data-beta-v1',
  version: 1,
  kind: 'student-beta',
  actId: 'act-7-data',
  unitId: 'lumi_protocol_act_7_data',
  lumiCourseId: 'lumi-season-1',
  title: 'ACT 7. DATA CORE (공개 베타)',
  description: 'list, split/join, tuple, dictionary를 실제 데이터 패킷으로 익히는 공개 베타 과정',
  persistencePolicy: 'official',
  rewardPolicy: 'standard-crystals',
  dailyRecordPolicy: 'official',
  assignmentEvidencePolicy: 'python-only',
  missions: LUMI_DATA_CORE_MISSIONS,
})
