/**
 * LUMI Algorithm Constellation — Python Concept & First Encounter Registry
 *
 * Invariant: Every newly introduced module, class, method, or builtin must have
 * an explicit First Encounter micro-lesson card (why -> tiny example -> syntax -> 10s prediction -> return)
 * so that students never face unexplained Python syntax.
 */

export const PYTHON_CONCEPT_REGISTRY = Object.freeze({
  'concept:function-body-focus': {
    conceptId: 'concept:function-body-focus',
    displayName: '함수 본문 작성하기 (def / return)',
    kind: 'structural-concept',
    canonicalFirstProblemId: 'AC-EXP-SEQ-01',
    why: '함수 이름과 매개변수 틀 안에서 핵심 계산을 작성하고 결과를 돌려줘요.',
    tinyExample: 'def run():\n    return 10',
    syntaxExample: 'def trace_rover_path(start, boost, scale, drift):\n    pos = start\n    return pos',
    predictionCheck: {
      prompt: '계산한 최종 결과를 호출한 곳으로 돌려줄 때 사용하는 명령은 무엇일까요?',
      options: ['return', 'def', 'print', 'pass'],
      expected: 'return',
    },
    protocolRepairId: 'PR-FN-BODY-001',
  },
  'operator:assignment': {
    conceptId: 'operator:assignment',
    displayName: '= (변수 대입과 덮어쓰기)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-EXP-SEQ-01',
    why: '오른쪽의 값을 왼쪽 변수에 넣어요. 이미 값이 있었다면 새 값으로 덮어씌워져요.',
    tinyExample: 'signal = 10\nsignal = 20  # 이제 signal은 20이에요',
    syntaxExample: 'signal = new_level',
    predictionCheck: {
      prompt: 'signal = 30 실행 후 signal = 70을 실행하면 최종 signal 값은 무엇일까요?',
      options: ['70', '30', '100', '3070'],
      expected: '70',
    },
    protocolRepairId: 'PR-ASSIGN-001',
  },
  'operator:arithmetic-state-update': {
    conceptId: 'operator:arithmetic-state-update',
    displayName: '사칙연산과 상태 갱신 (+, -, *)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-EXP-SEQ-01',
    why: '현재 변수의 값에 수를 더하거나 곱해서 다음 상태로 갱신해요.',
    tinyExample: 'pos = 2\npos = pos + 3  # pos는 5가 돼요',
    syntaxExample: 'pos = pos + boost\npos = pos * scale',
    predictionCheck: {
      prompt: 'pos = 2 실행 후 pos = pos * 3을 실행하면 pos는 얼마가 될까요?',
      options: ['6', '5', '3', '2'],
      expected: '6',
    },
    protocolRepairId: 'PR-ARITH-001',
  },
  'operator:comparison-bound': {
    conceptId: 'operator:comparison-bound',
    displayName: '<, <= (경계 비교 연산자)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-EXP-BOUND-05',
    why: '값이 경계보다 작은지(<) 또는 경계선까지 포함하는지(<=)를 비교할 때 사용해요.',
    tinyExample: '5 <= 5 → True\n5 < 5 → False',
    syntaxExample: 'return current_pos <= limit',
    predictionCheck: {
      prompt: '10 <= 10의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-BOUND-001',
  },
  'operator:comparison-lower-bound': {
    conceptId: 'operator:comparison-lower-bound',
    displayName: '>, >= (아래 경계와 비교하기)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-COND-ELIF-14',
    why: '값이 아래 경계보다 큰지(>) 또는 경계값까지 포함해 큰지(>=) 판정할 때 사용해요.',
    tinyExample: '5 >= 5 → True\n5 > 5 → False',
    syntaxExample: 'return score >= warning_line',
    predictionCheck: {
      prompt: '80 >= 80의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-LOWER-BOUND-001',
  },
  'statement:while': {
    conceptId: 'statement:while',
    displayName: 'while (조건이 참인 동안 반복하기)',
    kind: 'statement',
    canonicalFirstProblemId: 'AC-EXP-WHILE-07',
    why: '정해진 횟수가 아니라, 특정 조건이 만족되는 동안 계속 반복하다가 조건이 거짓이 되면 멈춰요.',
    tinyExample: 'while pos < target:\n    pos = pos + 1',
    syntaxExample: 'while pos < target:\n    pos = pos + 1',
    predictionCheck: {
      prompt: 'pos = 3, target = 3일 때 while pos < target: 본문은 실행될까요?',
      options: ['실행되지 않고 바로 끝난다', '1번 실행된다', '영원히 실행된다'],
      expected: '실행되지 않고 바로 끝난다',
    },
    protocolRepairId: 'PR-WHILE-001',
  },
  'value:boolean': {
    conceptId: 'value:boolean',
    displayName: 'True / False (참과 거짓)',
    kind: 'value-type',
    canonicalFirstProblemId: 'AC-COND-001',
    why: '조건이 맞는지 아닌지를 두 가지 상태로 표현할 때 사용해요.',
    tinyExample: 'gate_open = True',
    syntaxExample: 'return True  # 조건이 맞음',
    predictionCheck: {
      prompt: '잠긴 문이 열려 있지 않다면 gate_open은 무엇일까요?',
      options: ['False', 'True'],
      expected: 'False',
    },
    protocolRepairId: 'PR-BOOL-001',
  },
  'operator:and': {
    conceptId: 'operator:and',
    displayName: 'and (두 조건 모두)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-COND-001',
    why: '두 조건이 모두 참일 때만 통과시키는 규칙을 만들어요.',
    tinyExample: 'True and False → False',
    syntaxExample: 'return switch1 and switch2',
    predictionCheck: {
      prompt: 'True and True의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-AND-001',
  },
  'operator:or': {
    conceptId: 'operator:or',
    displayName: 'or (둘 중 하나라도)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-COND-002',
    why: '여러 조건 중 하나라도 참이면 통과시키는 규칙을 만들어요.',
    tinyExample: 'True or False → True',
    syntaxExample: 'return has_card or emergency_approved',
    predictionCheck: {
      prompt: 'False or True의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-OR-001',
  },
  'operator:not': {
    conceptId: 'operator:not',
    displayName: 'not (참과 거짓 반전)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-COND-NOT-13',
    why: 'Boolean 상태를 반대로 바꿀 때 사용해요.',
    tinyExample: 'not True → False\nnot False → True',
    syntaxExample: 'return not silent_mode',
    predictionCheck: {
      prompt: 'not False의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-NOT-001',
  },
  'statement:elif': {
    conceptId: 'statement:elif',
    displayName: 'if / elif / else (순서 있는 여러 갈래)',
    kind: 'statement',
    canonicalFirstProblemId: 'AC-COND-ELIF-14',
    why: '조건을 위에서부터 확인하고 처음 참인 한 갈래만 실행해요.',
    tinyExample: 'if score >= 80:\n    return "A"\nelif score >= 50:\n    return "B"\nelse:\n    return "C"',
    syntaxExample: 'if condition1:\n    ...\nelif condition2:\n    ...\nelse:\n    ...',
    predictionCheck: {
      prompt: '첫 if 조건이 True라면 다음 elif 조건은 검사할까요?',
      options: ['검사하지 않는다', '항상 검사한다'],
      expected: '검사하지 않는다',
    },
    protocolRepairId: 'PR-ELIF-001',
  },
  'builtin:list': {
    conceptId: 'builtin:list',
    displayName: 'list (순서가 있는 목록)',
    kind: 'builtin-type',
    canonicalFirstProblemId: 'AC-CODE-FIRST-ERROR-01',
    why: '여러 값을 도착한 순서대로 보관하고 위치 번호로 하나씩 확인할 때 사용해요.',
    tinyExample: "signals = ['A', 'B', 'C']",
    syntaxExample: 'first = signals[0]',
    predictionCheck: {
      prompt: "items = [4, 7, 9]일 때 items[1]은 무엇일까요?",
      options: ['7', '4', '9', '1'],
      expected: '7',
    },
    protocolRepairId: 'PR-LIST-000',
  },
  'statement:for': {
    conceptId: 'statement:for',
    displayName: 'for (하나씩 순회하기)',
    kind: 'statement',
    canonicalFirstProblemId: 'AC-EXP-LOOP-06',
    why: '목록의 값을 처음부터 끝까지 빠뜨리지 않고 하나씩 살펴볼 때 사용해요.',
    tinyExample: 'for signal in signals:\n    check(signal)',
    syntaxExample: 'for item in items:\n    # item을 확인해요',
    predictionCheck: {
      prompt: 'items에 값이 3개 있다면 for 본문은 기본적으로 몇 번 실행될까요?',
      options: ['3번', '2번', '1번', '계속 실행'],
      expected: '3번',
    },
    protocolRepairId: 'PR-FOR-001',
  },
  'statement:if': {
    conceptId: 'statement:if',
    displayName: 'if (조건에 따라 선택하기)',
    kind: 'statement',
    canonicalFirstProblemId: 'AC-CODE-FIRST-ERROR-01',
    why: '조건이 참인 경우에만 특정 행동을 실행할 때 사용해요.',
    tinyExample: 'if energy < 0:\n    return "error"',
    syntaxExample: 'if condition:\n    # 조건이 True일 때 실행',
    predictionCheck: {
      prompt: 'energy가 -2일 때 if energy < 0의 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-IF-001',
  },
  'builtin:min': {
    conceptId: 'builtin:min',
    displayName: 'min() (가장 작은 값 찾기)',
    kind: 'builtin-function',
    canonicalFirstProblemId: 'AC-SORT-MIN-01',
    why: '여러 값 가운데 가장 작은 값을 한 번에 찾을 때 사용해요.',
    tinyExample: 'min([7, 3, 5]) → 3',
    syntaxExample: 'smallest = min(cargos)',
    predictionCheck: {
      prompt: 'min([8, 2, 6])의 결과는 무엇일까요?',
      options: ['2', '8', '6', '3'],
      expected: '2',
    },
    protocolRepairId: 'PR-MIN-001',
  },
  'syntax:swap': {
    conceptId: 'syntax:swap',
    displayName: 'a, b = b, a (두 값 교환)',
    kind: 'syntax',
    canonicalFirstProblemId: 'AC-SORT-MIN-01',
    why: '두 위치의 값을 임시 상자 없이 서로 바꿀 때 사용해요.',
    tinyExample: 'a = 3, b = 7 → a, b = b, a → a = 7, b = 3',
    syntaxExample: 'cargos[0], cargos[min_idx] = cargos[min_idx], cargos[0]',
    predictionCheck: {
      prompt: 'a = 2, b = 5에서 a, b = b, a를 실행하면 a는 무엇일까요?',
      options: ['5', '2', '7', '0'],
      expected: '5',
    },
    protocolRepairId: 'PR-SWAP-001',
  },
  'operator:modulo': {
    conceptId: 'operator:modulo',
    displayName: '% (나머지 연산자)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-PAT-003',
    why: '나눈 뒤 남은 나머지를 구해서 반복되는 주기를 찾아요.',
    tinyExample: '7을 3으로 나누면 몫은 2이고 나머지는 1이에요.',
    syntaxExample: 'remain = time % 3',
    predictionCheck: {
      prompt: '5 % 2의 계산 결과는 무엇일까요?',
      options: ['1', '2', '0', '5'],
      expected: '1',
    },
    protocolRepairId: 'PR-MOD-001',
  },
  'operator:equality': {
    conceptId: 'operator:equality',
    displayName: '==, != (값의 일치 여부 비교)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-PAT-003',
    why: '두 값이 서로 같은지(==) 또는 다른지(!=)를 비교하여 True나 False로 판정해요.',
    tinyExample: '7 % 3 == 1 → True\n4 != 4 → False',
    syntaxExample: 'return current_time % 3 == 0',
    predictionCheck: {
      prompt: '8 % 4 == 0의 계산 결과는 무엇일까요?',
      options: ['True', 'False'],
      expected: 'True',
    },
    protocolRepairId: 'PR-EQUALITY-001',
  },
  'operator:floor-division': {
    conceptId: 'operator:floor-division',
    displayName: '// (정수 나눗셈 몫 연산자)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-PAT-DIGIT-24',
    why: '나눗셈에서 소수점을 버리고 정수 몫만 남겨서 낮은 자릿수를 분리하거나 제거할 때 사용해요.',
    tinyExample: '472 // 10 → 47\n472 // 100 → 4',
    syntaxExample: 'hundreds = number // 100\nremaining = number // 10',
    predictionCheck: {
      prompt: '85 // 10의 계산 결과는 무엇일까요?',
      options: ['8', '8.5', '5', '0'],
      expected: '8',
    },
    protocolRepairId: 'PR-FLOOR-DIV-001',
  },
  'builtin:set': {
    conceptId: 'builtin:set',
    displayName: 'set (집합/중복 제거)',
    kind: 'builtin-type',
    canonicalFirstProblemId: 'AC-SET-UNIQUE-01',
    why: '여러 개 섞여 있는 데이터에서 중복을 없애고 서로 다른 종류만 모을 때 사용해요.',
    tinyExample: "['철', '철', '얼음', '철'] → {'철', '얼음'}",
    syntaxExample: 'kinds = set(items)',
    predictionCheck: {
      prompt: "set(['A', 'B', 'A', 'C'])에 들어 있는 원소의 개수는 몇 개일까요?",
      options: ['3', '4', '2', '1'],
      expected: '3',
    },
    protocolRepairId: 'PR-SET-001',
  },
  'builtin:len': {
    conceptId: 'builtin:len',
    displayName: 'len() (항목 개수 재기)',
    kind: 'builtin-function',
    canonicalFirstProblemId: 'AC-SET-UNIQUE-01',
    why: '목록·문자열·집합 안에 항목이 몇 개 있는지 숫자로 알려줘요.',
    tinyExample: 'len(["A", "B", "C"])  # 3',
    syntaxExample: 'count = len(items)',
    predictionCheck: {
      prompt: 'len([5, 5, 9, 1])의 결과는 얼마일까요?',
      options: ['4', '3', '5', '1'],
      expected: '4',
    },
    protocolRepairId: 'PR-LEN-001',
  },
  'operator:membership-in': {
    conceptId: 'operator:membership-in',
    displayName: 'in (포함 여부 확인)',
    kind: 'operator',
    canonicalFirstProblemId: 'AC-SET-MEMBERSHIP-42',
    why: '찾는 값이 목록이나 집합 안에 있으면 True, 없으면 False가 돼요.',
    tinyExample: '"B" in {"A", "B"}  # True',
    syntaxExample: 'exists = item in collection',
    predictionCheck: {
      prompt: '"C" in {"A", "B"}의 결과는 무엇일까요?',
      options: ['False', 'True'],
      expected: 'False',
    },
    protocolRepairId: 'PR-IN-001',
  },
  'method:set_add': {
    conceptId: 'method:set_add',
    displayName: '.add() (세트에 원소 추가)',
    kind: 'method',
    canonicalFirstProblemId: 'AC-SET-INTERSECT-43',
    why: '새로운 값을 세트에 넣어요. 이미 있는 값이면 저절로 무시돼요.',
    tinyExample: 'seen.add("A")',
    syntaxExample: 'visited.add(planet_id)',
    predictionCheck: {
      prompt: 's = set(); s.add(1); s.add(1) 실행 후 len(s)는 얼마일까요?',
      options: ['1', '2', '0'],
      expected: '1',
    },
    protocolRepairId: 'PR-SET-002',
  },
  'class:deque': {
    conceptId: 'class:deque',
    displayName: 'collections.deque (양방향 대기열)',
    kind: 'module-class',
    canonicalFirstProblemId: 'AC-NAV-005',
    why: '먼저 도착한 데이터를 먼저 처리(FIFO)하거나 앞뒤로 빠르게 꺼낼 때 써요.',
    tinyExample: '대기 줄 [A, B, C]에서 A가 먼저 나가요.',
    syntaxExample: 'from collections import deque\nqueue = deque(["A", "B"])',
    predictionCheck: {
      prompt: '대기열(Queue)에서 가장 먼저 나가는 데이터는 어느 쪽일까요?',
      options: ['가장 먼저 들어온 앞쪽(Front)', '가장 나중에 들어온 뒤쪽(Back)', '무작위 위치'],
      expected: '가장 먼저 들어온 앞쪽(Front)',
    },
    protocolRepairId: 'PR-DEQUE-001',
  },
  'method:popleft': {
    conceptId: 'method:popleft',
    displayName: '.popleft() (맨 앞 데이터 꺼내기)',
    kind: 'method',
    canonicalFirstProblemId: 'AC-NAV-005',
    why: '대기열의 맨 앞(왼쪽)에서 대기하던 첫 번째 손님/신호를 꺼내요.',
    tinyExample: 'first_signal = queue.popleft()',
    syntaxExample: 'current = queue.popleft()',
    predictionCheck: {
      prompt: "q = deque(['A', 'B']); item = q.popleft() 실행 후 item은 무엇일까요?",
      options: ["'A'", "'B'", "['A', 'B']"],
      expected: "'A'",
    },
    protocolRepairId: 'PR-DEQUE-002',
  },
  'method:append': {
    conceptId: 'method:append',
    displayName: '.append() (맨 뒤에 추가하기)',
    kind: 'method',
    canonicalFirstProblemId: 'AC-SEQ-RUNNING-35',
    why: '목록의 가장 뒤에 새로운 데이터를 덧붙여요.',
    tinyExample: 'box = []; box.append(10) → [10]',
    syntaxExample: 'collected.append(capsule)',
    predictionCheck: {
      prompt: 'a = [1, 2]; a.append(3) 실행 후 a의 길이는 얼마일까요?',
      options: ['3', '2', '4', '1'],
      expected: '3',
    },
    protocolRepairId: 'PR-LIST-001',
  },
  'builtin:range': {
    conceptId: 'builtin:range',
    displayName: 'range() (숫자 범위 생성기)',
    kind: 'builtin-function',
    canonicalFirstProblemId: 'AC-EXP-LOOP-06',
    why: '원하는 시작부터 끝 전까지의 연속된 숫자를 순서대로 만들어요.',
    tinyExample: 'range(0, 3) → 0, 1, 2',
    syntaxExample: 'for i in range(len(items) - 1, -1, -1):',
    predictionCheck: {
      prompt: 'list(range(1, 4))의 결과는 무엇일까요?',
      options: ['[1, 2, 3]', '[1, 2, 3, 4]', '[0, 1, 2, 3]'],
      expected: '[1, 2, 3]',
    },
    protocolRepairId: 'PR-RANGE-001',
  },
  'syntax:slicing': {
    conceptId: 'syntax:slicing',
    displayName: '[start:end:step] (슬라이싱)',
    kind: 'syntax',
    canonicalFirstProblemId: 'AC-STR-REVERSE-01',
    why: '문자열이나 리스트의 일부분을 잘라내거나 뒤집을 때 사용해요.',
    tinyExample: "'LUMI'[::-1] → 'IMUL'",
    syntaxExample: 'reversed_text = text[::-1]',
    predictionCheck: {
      prompt: "'ABC' [::-1]의 결과는 무엇일까요?",
      options: ["'CBA'", "'ABC'", "'BCA'"],
      expected: "'CBA'",
    },
    protocolRepairId: 'PR-SLICE-001',
  },
  'builtin:dict': {
    conceptId: 'builtin:dict',
    displayName: 'dict / {} (이름표가 붙은 기록표)',
    kind: 'builtin-type',
    canonicalFirstProblemId: 'AC-DICT-FREQ-44',
    why: '항목의 이름을 key로, 그 항목에 대한 수량이나 횟수를 value로 연결해 기억할 때 사용해요.',
    tinyExample: "A가 2번, B가 1번 → {'A': 2, 'B': 1}",
    syntaxExample: "counts = {}\ncounts['A'] = 1",
    predictionCheck: {
      prompt: "{'A': 2, 'B': 1}에서 'A' 이름표의 값은 무엇일까요?",
      options: ['2', '1', 'A', '3'],
      expected: '2',
    },
    protocolRepairId: 'PR-DICT-001',
  },
})

export function getConceptDetails(conceptId) {
  return PYTHON_CONCEPT_REGISTRY[conceptId] || null
}

export function getConceptsNeededForProblem(problemId, kernelConcepts = {}) {
  const conceptIds = [...new Set([
    ...(kernelConcepts.requires || []),
    ...(kernelConcepts.introduces || []),
  ])]
  return conceptIds.map((id) => PYTHON_CONCEPT_REGISTRY[id]).filter(Boolean)
}

// Backward-compatible alias for callers created before required-concept repair.
export const getIntroducedConceptsForProblem = getConceptsNeededForProblem
