import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import PublicApplication from '../pages/PublicApplication.jsx';
import './math-application.css';
import {mathMarketingWindow, mathAttribution, trackMath} from '../utils/mathFunnel.js';
const marketingWindow=mathMarketingWindow();
const isMiddle = new URLSearchParams(window.location.search).get('course') === 'middle';
const courseName = isMiddle ? '중등수학' : '수학과 고전읽기';
document.title = `${courseName} 7일 무료체험 신청서`;
const sourceAttribution=mathAttribution(marketingWindow?.location.search || '');
const target=document.getElementById('math-application');
if(target)createRoot(target).render(<MemoryRouter><PublicApplication fixedType="trial" initialCourse={courseName} sourceAttribution={sourceAttribution ? `[${courseName} 소개 페이지] ${sourceAttribution}` : ''} onMarketingEvent={trackMath} /></MemoryRouter>);
