import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import PublicApplication from '../pages/PublicApplication.jsx';
import './math-application.css';
import {mathMarketingWindow, mathAttribution, trackMath} from '../utils/mathFunnel.js';
const marketingWindow=mathMarketingWindow();
const sourceAttribution=mathAttribution(marketingWindow?.location.search || '');
const target=document.getElementById('math-application');
if(target)createRoot(target).render(<MemoryRouter><PublicApplication fixedType="trial" initialCourse="수학과 고전읽기" sourceAttribution={sourceAttribution ? `[초등수학 소개 페이지] ${sourceAttribution}` : ''} onMarketingEvent={trackMath} /></MemoryRouter>);
