export const STUDY_CREW_MISSION_MAX_LENGTH = 60;

export const STUDY_CREW_DAILY_MISSIONS = [
  { id: 'life_movie_quote', category: '아이스브레이킹', title: '인생 영화 명대사', prompt: '나의 인생 영화 속 명대사 하나를 적어보세요.' },
  { id: 'million_won_first_buy', category: '아이스브레이킹', title: '100만 원이 생긴다면', prompt: '지금 당장 100만 원이 생긴다면 가장 먼저 사고 싶은 것을 적어보세요.' },
  { id: 'favorite_season', category: '아이스브레이킹', title: '좋아하는 계절', prompt: '내가 가장 좋아하는 계절과 그 이유를 짧게 적어보세요.' },
  { id: 'tiny_talent', category: '아이스브레이킹', title: '사소한 특기', prompt: '남들은 잘 모르는 나만의 아주 사소한 특기를 알려주세요.' },
  { id: 'phone_wallpaper_mood', category: '아이스브레이킹', title: '배경화면 분위기', prompt: '현재 내 핸드폰 배경화면의 분위기를 말해보세요. 개인사진 설명은 피해주세요.' },
  { id: 'funniest_meme', category: '아이스브레이킹', title: '최근 웃긴 밈', prompt: '최근에 가장 웃겼던 밈이나 짤을 간단히 설명해보세요.' },
  { id: 'never_buy_food', category: '아이스브레이킹', title: '절대 안 사 먹는 음식', prompt: '내가 돈 주고는 절대 사 먹지 않는 음식 한 가지를 적어보세요.' },
  { id: 'morning_first_action', category: '아이스브레이킹', title: '아침 첫 행동', prompt: '아침에 눈 떠서 가장 먼저 하는 행동을 적어보세요.' },
  { id: 'satisfying_purchase', category: '아이스브레이킹', title: '만족 소비', prompt: '최근에 돈을 쓰고 가장 만족했던 소비를 적어보세요.' },
  { id: 'three_hashtags', category: '아이스브레이킹', title: '나를 표현하는 해시태그', prompt: '나를 표현하는 해시태그 3가지를 적어보세요.' },
  { id: 'desert_island_three', category: '아이스브레이킹', title: '무인도 3가지', prompt: '무인도에 떨어졌을 때 꼭 가져갈 딱 3가지 아이템을 골라보세요.' },
  { id: 'life_bgm', category: '아이스브레이킹', title: '내 인생의 BGM', prompt: '내 인생의 BGM을 하나 고른다면 어떤 곡일지 적어보세요.' },
  { id: 'ramen_recipe', category: '아이스브레이킹', title: '라면 조리법', prompt: '가장 좋아하는 라면 조리법을 짧게 소개해보세요.' },
  { id: 'childhood_dream', category: '아이스브레이킹', title: '어릴 적 장래희망', prompt: '어릴 적 나의 장래희망은 무엇이었나요?' },
  { id: 'lottery_first_tell', category: '아이스브레이킹', title: '복권 1등 소식', prompt: '복권 1등에 당첨된다면 누구에게 가장 먼저 알릴지 적어보세요.' },
  { id: 'favorite_time_of_day', category: '아이스브레이킹', title: '좋아하는 시간대', prompt: '하루 중 내가 가장 좋아하는 시간대는 언제인가요?' },
  { id: 'sweet_sour_pork', category: '아이스브레이킹', title: '탕수육 취향', prompt: '탕수육은 부먹, 찍먹, 아니면 다른 방법인지 적어보세요.' },
  { id: 'stress_playlist', category: '아이스브레이킹', title: '스트레스 해소곡', prompt: '나만의 스트레스 해소용 플레이리스트 첫 번째 곡을 적어보세요.' },
  { id: 'recent_youtube', category: '아이스브레이킹', title: '최근 유튜브 추천', prompt: '최근 본 유튜브 영상 중 유익했거나 재밌었던 것을 소개해보세요.' },
  { id: 'daily_ready_routine', category: '아이스브레이킹', title: '하루 시작 루틴', prompt: '하루를 시작할 때 꼭 하는 준비 루틴 하나를 적어보세요.' },
  { id: 'weather_mood', category: '정서 공유', title: '오늘 기분 날씨', prompt: '오늘 아침 일어났을 때의 기분을 날씨로 표현해보세요.' },
  { id: 'recent_big_laugh', category: '정서 공유', title: '크게 웃었던 일', prompt: '최근 나를 가장 크게 웃게 했던 일을 짧게 적어보세요.' },
  { id: 'mind_thought', category: '정서 공유', title: '요즘 머릿속 생각', prompt: '요즘 나의 머릿속을 가장 많이 차지하는 생각을 적어보세요.' },
  { id: 'self_praise', category: '정서 공유', title: '나에게 칭찬', prompt: '나 자신에게 해주고 싶은 칭찬 한마디를 남겨보세요.' },
  { id: 'today_expected_moment', category: '정서 공유', title: '기대되는 순간', prompt: '오늘 하루 중 가장 기대되는 순간을 적어보세요.' },
  { id: 'touching_moment', category: '정서 공유', title: '뭉클했던 순간', prompt: '최근에 뭉클했거나 마음이 움직였던 순간을 적어보세요.' },
  { id: 'calm_sentence', category: '멘탈 케어', title: '마법의 문장', prompt: '마음이 불안할 때 나를 진정시키는 문장 하나를 적어보세요.' },
  { id: 'comfort_words', category: '멘탈 케어', title: '위로받는 말', prompt: '내가 가장 위로받는다고 느끼는 행동이나 말을 적어보세요.' },
  { id: 'energy_score', category: '정서 공유', title: '오늘 에너지 점수', prompt: '오늘 나의 에너지를 1에서 100까지 숫자로 표현해보세요.' },
  { id: 'thankful_person', category: '정서 공유', title: '고마웠던 사람', prompt: '요 며칠 사이 가장 고마웠던 사람과 그 이유를 짧게 적어보세요.' },
  { id: 'current_fear', category: '멘탈 케어', title: '가로막는 두려움', prompt: '현재 나를 가로막고 있다고 느껴지는 두려움 하나를 적어보세요.' },
  { id: 'comfort_scent', category: '정서 공유', title: '편안한 향기', prompt: '나를 가장 편안하게 만드는 냄새나 향기를 적어보세요.' },
  { id: 'burnout_recovery', category: '멘탈 케어', title: '번아웃 극복법', prompt: '번아웃이 왔을 때 나만의 극복 방법을 적어보세요.' },
  { id: 'end_day_feeling', category: '정서 공유', title: '하루 끝 감정', prompt: '오늘 하루를 끝내고 느끼고 싶은 감정을 적어보세요.' },
  { id: 'anger_calm_routine', category: '멘탈 케어', title: '마음 진정 루틴', prompt: '화가 났을 때 마음을 가라앉히는 나만의 루틴을 적어보세요.' },
  { id: 'warm_words_needed', category: '멘탈 케어', title: '듣고 싶은 말', prompt: '지금 당장 누군가에게 듣고 싶은 따뜻한 말 한마디를 적어보세요.' },
  { id: 'relieved_moment', category: '정서 공유', title: '안도했던 순간', prompt: '요 근래 가장 크게 안도했던 순간을 적어보세요.' },
  { id: 'exciting_word', category: '정서 공유', title: '설레는 단어', prompt: '나를 가장 설레게 만드는 단어 하나를 적어보세요.' },
  { id: 'soul_food', category: '멘탈 케어', title: '소울푸드', prompt: '기분이 가라앉을 때 꼭 먹고 싶은 나만의 소울푸드를 적어보세요.' },
  { id: 'emotion_emojis', category: '정서 공유', title: '감정 이모지 3개', prompt: '오늘 하루 나의 감정 상태를 이모지 3개로 표현해보세요.' },
  { id: 'tiny_week_goal', category: '스터디 연대감', title: '이번 주 작은 목표', prompt: '이번 주 스터디에서 꼭 이루고 싶은 아주 작은 목표를 적어보세요.' },
  { id: 'self_motivation_words', category: '스터디 연대감', title: '나를 움직이는 말', prompt: '공부가 정말 안 될 때 나를 움직이게 하는 말을 적어보세요.' },
  { id: 'crew_tip', category: '스터디 연대감', title: '나만의 꿀팁', prompt: '크루원들에게 추천하고 싶은 나만의 꿀팁을 적어보세요.' },
  { id: 'respected_person', category: '성장', title: '존경하는 인물', prompt: '내가 가장 존경하는 인물과 그 이유를 짧게 적어보세요.' },
  { id: 'one_year_later', category: '성장', title: '1년 뒤 나', prompt: '1년 뒤 나의 모습을 한 문장으로 상상해보세요.' },
  { id: 'rewarding_study', category: '스터디 연대감', title: '보람 있었던 순간', prompt: '스터디를 하면서 가장 보람을 느꼈던 순간을 적어보세요.' },
  { id: 'wake_up_trick', category: '스터디 연대감', title: '졸릴 때 필살기', prompt: '공부하다 졸릴 때 잠을 깨는 나만의 필살기를 적어보세요.' },
  { id: 'today_reward', category: '스터디 연대감', title: '오늘의 작은 보상', prompt: '오늘 공부를 끝내고 나에게 줄 작은 보상을 적어보세요.' },
  { id: 'good_crew_condition', category: '스터디 연대감', title: '좋은 크루 조건', prompt: '내가 생각하는 좋은 스터디 크루의 조건 한 가지를 적어보세요.' },
  { id: 'light_worry', category: '스터디 연대감', title: '가벼운 고민거리', prompt: '크루원들에게 묻고 싶은 가벼운 고민거리를 적어보세요.' },
  { id: 'recent_quote', category: '성장', title: '인상 깊은 구절', prompt: '최근 읽은 책이나 글에서 인상 깊었던 구절을 적어보세요.' },
  { id: 'slump_signal', category: '성장', title: '슬럼프 신호', prompt: '슬럼프가 왔을 때 그것을 알아차리는 나만의 신호를 적어보세요.' },
  { id: 'avoid_distraction', category: '스터디 연대감', title: '딴짓 참는 법', prompt: '스터디 중 딴짓하고 싶을 때 참아내는 방법을 적어보세요.' },
  { id: 'letter_to_future', category: '성장', title: '10년 뒤 나에게', prompt: '10년 뒤의 나에게 쓰고 싶은 짧은 편지를 적어보세요.' },
  { id: 'today_keywords', category: '학습 시작', title: '오늘의 키워드 3개', prompt: '오늘 배울 내용 중 중요하다고 생각하는 키워드 3개를 적어보세요.' },
  { id: 'crew_strength', category: '스터디 연대감', title: '크루원의 장점', prompt: '같이 공부하는 크루원들의 장점 한 가지를 적어보세요.' },
  { id: 'study_reason_three', category: '성장', title: '공부하는 이유 세 글자', prompt: '내가 공부하는 이유를 세 글자로 표현해보세요.' },
  { id: 'focus_enemy', category: '스터디 연대감', title: '집중 방해꾼', prompt: '나의 집중력을 갉아먹는 가장 큰 방해꾼을 적어보세요.' },
  { id: 'phone_less_promise', category: '스터디 연대감', title: '스마트폰 줄이기', prompt: '오늘 스마트폰 사용 시간을 줄이기 위한 다짐을 적어보세요.' },
  { id: 'monthly_finish', category: '성장', title: '이번 달 끝낼 것', prompt: '이번 달에 꼭 끝내고 싶은 책이나 강의 이름을 적어보세요.' },
  { id: 'animal_rebirth', category: '상상력', title: '동물로 환생한다면', prompt: '내가 동물로 환생한다면 어떤 동물일지 적어보세요.' },
  { id: 'time_machine', category: '상상력', title: '타임머신 여행', prompt: '타임머신을 탄다면 과거와 미래 중 어디로 가고 싶은지 적어보세요.' },
  { id: 'zombie_first_action', category: '상상력', title: '좀비 사태 첫 행동', prompt: '좀비 사태가 터지면 내가 가장 먼저 할 행동을 적어보세요.' },
  { id: 'name_acrostic', category: '상상력', title: '내 이름 삼행시', prompt: '내 이름으로 짧은 삼행시를 지어보세요.' },
  { id: 'alien_food', category: '상상력', title: '외계인 추천 음식', prompt: '외계인에게 지구 음식 하나만 추천한다면 무엇을 고를지 적어보세요.' },
  { id: 'movie_director', category: '상상력', title: '내가 영화 감독이라면', prompt: '내가 영화 감독이라면 어떤 장르의 영화를 만들고 싶은가요?' },
  { id: 'life_drama_episode', category: '상상력', title: '내 인생 드라마', prompt: '내 인생을 드라마로 만든다면 지금은 몇 화쯤일지 적어보세요.' },
  { id: 'telepathy_message', category: '상상력', title: '10초 텔레파시', prompt: '전 세계 사람들에게 10초 동안 텔레파시를 보낸다면 할 말을 적어보세요.' },
  { id: 'one_color_clothes', category: '상상력', title: '평생 한 가지 색', prompt: '평생 한 가지 색깔 옷만 입어야 한다면 무슨 색을 고를지 적어보세요.' },
  { id: 'history_dinner', category: '상상력', title: '역사 속 저녁 식사', prompt: '역사 속 인물 한 명과 저녁 식사를 한다면 누구와 하고 싶은가요?' },
  { id: 'teleport_place', category: '상상력', title: '순간이동 장소', prompt: '지금 당장 순간이동할 수 있다면 가고 싶은 곳을 적어보세요.' },
  { id: 'useless_power', category: '상상력', title: '쓸모없는 초능력', prompt: '나에게 쓸모없는 초능력이 하나 생긴다면 무엇일지 적어보세요.' },
  { id: 'invisible_kind_prank', category: '상상력', title: '투명인간 선의의 장난', prompt: '투명인간이 된다면 해보고 싶은 선의의 장난을 적어보세요.' },
  { id: 'back_to_ten', category: '상상력', title: '10살로 돌아간다면', prompt: '자고 일어났는데 10살로 돌아갔다면 가장 먼저 할 일을 적어보세요.' },
  { id: 'secret_room', category: '상상력', title: '비밀의 방', prompt: '내 방에 비밀의 방이 있다면 무엇으로 채우고 싶은지 적어보세요.' },
  { id: 'robot_world', category: '상상력', title: '로봇이 일하는 세상', prompt: '로봇이 모든 일을 다 해주는 세상이 온다면 나는 무엇을 할지 적어보세요.' },
  { id: 'teleport_vs_flight', category: '밸런스 게임', title: '텔레포트 vs 비행', prompt: '텔레포트와 비행 능력 중 하나를 고른다면 무엇을 고를지 적어보세요.' },
  { id: 'inventor_item', category: '상상력', title: '기상천외한 발명품', prompt: '내가 발명가라면 만들고 싶은 기상천외한 물건을 적어보세요.' },
  { id: 'money_vs_internet', category: '밸런스 게임', title: '100억 vs 인터넷', prompt: '100억을 받는 대신 평생 인터넷 끊기, 가능할지 적어보세요.' },
  { id: 'alien_word', category: '상상력', title: '나만의 외계어', prompt: '나만 아는 외계어 단어 하나를 만들고 뜻을 설명해보세요.' },
  { id: 'summer_vs_winter', category: '밸런스 게임', title: '평생 여름 vs 겨울', prompt: '평생 여름과 평생 겨울 중 하나를 고르고 이유를 적어보세요.' },
  { id: 'money_probability', category: '밸런스 게임', title: '확실한 돈 vs 큰 기회', prompt: '1000만 원 확정과 10% 확률 100억 중 하나를 고르고 이유를 적어보세요.' },
  { id: 'success_standard', category: '가치관', title: '성공의 기준', prompt: '내가 생각하는 성공의 기준은 무엇인지 적어보세요.' },
  { id: 'relationship_value', category: '가치관', title: '인간관계 가치', prompt: '인간관계에서 내가 가장 중요하게 생각하는 가치를 적어보세요.' },
  { id: 'travel_j_or_p', category: '가치관', title: '여행 계획형 vs 즉흥형', prompt: '친구와 여행 갈 때 나는 계획형인지 즉흥형인지 적어보세요.' },
  { id: 'life_motto', category: '가치관', title: '나의 모토', prompt: '나의 좌우명이나 인생의 모토를 적어보세요.' },
  { id: 'no_sleep_vs_no_weight', category: '밸런스 게임', title: '피곤 없음 vs 살 안 찜', prompt: '잠 안 자도 안 피곤한 약과 많이 먹어도 살 안 찌는 약 중 골라보세요.' },
  { id: 'misunderstanding_style', category: '가치관', title: '오해받았을 때', prompt: '오해받았을 때 적극 해명하는 편인지 그냥 두는 편인지 적어보세요.' },
  { id: 'turning_point', category: '가치관', title: '인생 전환점', prompt: '내 인생에서 큰 전환점이 되었던 사건을 적어보세요.' },
  { id: 'like_vs_liked', category: '밸런스 게임', title: '좋아하는 사람 vs 나를 좋아하는 사람', prompt: '좋아하는 사람과 나를 좋아하는 사람 중 하나를 고르고 이유를 적어보세요.' },
  { id: 'brave_moment', category: '가치관', title: '용기를 낸 순간', prompt: '살면서 가장 큰 용기를 냈던 순간을 적어보세요.' },
  { id: 'perfect_vs_fast', category: '가치관', title: '완벽주의 vs 실행력', prompt: '완벽주의와 빠른 실행력 중 더 중요하다고 생각하는 것을 적어보세요.' },
  { id: 'future_self_feeling', category: '가치관', title: '미래의 나', prompt: '미래의 나에 대해 기대되는 점이나 걱정되는 점을 하나 적어보세요.' },
  { id: 'snack_vs_late_sleep', category: '밸런스 게임', title: '간식 끊기 vs 늦잠 끊기', prompt: '평생 간식 끊기와 평생 늦잠 끊기 중 하나를 고르고 이유를 적어보세요.' },
  { id: 'life_hobby', category: '가치관', title: '삶의 활력소', prompt: '내 삶의 활력소가 되어주는 취미 생활을 적어보세요.' },
  { id: 'money_cannot_buy', category: '가치관', title: '돈으로 못 사는 것', prompt: '돈으로 살 수 없는 것 중 가장 가치 있다고 생각하는 것을 적어보세요.' },
  { id: 'past_vs_future', category: '밸런스 게임', title: '과거 수정 vs 미래 보기', prompt: '과거 실수 고치기와 미래 성공 미리 보기 중 하나를 골라보세요.' },
  { id: 'perfect_weekend', category: '가치관', title: '완벽한 주말', prompt: '내가 가장 행복하다고 느끼는 완벽한 주말의 모습을 적어보세요.' },
  { id: 'life_intro_sentence', category: '가치관', title: '내 인생 소개 문구', prompt: '내 인생을 소개하는 문구에 적고 싶은 한 문장을 적어보세요.' },
  { id: 'text_clap', category: '서로 응원', title: '나에게 텍스트 박수', prompt: '오늘 이 미션을 읽고 있는 나에게 짧은 텍스트 박수를 보내보세요.' },
];

export function getTodayStudyCrewMissionKey() {
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul' }).format(new Date());
}

export function getStudyCrewMissionForDate(dateKey) {
  const parts = String(dateKey || '').split('-').map(Number);
  if (parts.length < 3 || !parts[0] || !parts[1] || !parts[2]) {
    return STUDY_CREW_DAILY_MISSIONS[0];
  }
  const [year, month, day] = parts;
  const daysSinceEpoch = Math.floor(Date.UTC(year, month - 1, day) / 86400000);
  const total = STUDY_CREW_DAILY_MISSIONS.length;
  const index = ((daysSinceEpoch % total) + total) % total;
  return STUDY_CREW_DAILY_MISSIONS[index];
}
