/**
 * LUMI Algorithm Constellation — Complete 100 Editorial Catalog
 *
 * Invariants:
 * 1. Exactly 76 Core + 20 Branch + 4 Capstone = 100 Problems across 10 Constellations.
 * 2. Unambiguous catalogOrder (1..100) strictly assigned.
 * 3. Stable meaningful problemIds. Existing 7 IDs preserved for 100% backward-compatibility.
 * 4. Existing released kernels stay published; new capability kernels remain
 *    prototypes until accessibility and student-pilot gates pass.
 * 5. Detailed provenance and rightsStatus for every single problem.
 */

export const ALGORITHM_EDITORIAL_CATALOG = Object.freeze([
  // ==========================================
  // 성단 0. 사고 탐사 면허 (Constellation 0) — 1~10
  // ==========================================
  {
    problemId: 'AC-EXP-SEQ-01',
    catalogOrder: 1,
    constellationId: 'constellation-0',
    studentTitle: '루미의 세 명령',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: [],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '순차 실행과 상태 추적' },
  },
  {
    problemId: 'AC-EXP-VAR-02',
    catalogOrder: 2,
    constellationId: 'constellation-0',
    studentTitle: '사라진 변수 값',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-EXP-SEQ-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '변수 대입과 덮어쓰기' },
  },
  {
    problemId: 'AC-EXP-STEP-03',
    catalogOrder: 3,
    constellationId: 'constellation-0',
    studentTitle: '빠진 명령 한 장',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-EXP-VAR-02'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '절차 분해 및 빠진 명령 선택 조립' },
  },
  {
    problemId: 'AC-EXP-SWAP-04',
    catalogOrder: 4,
    constellationId: 'constellation-0',
    studentTitle: '바뀌어 버린 두 화물',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-EXP-VAR-02'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '정보 소실 전 temp 백업 전략' },
  },
  {
    problemId: 'AC-EXP-BOUND-05',
    catalogOrder: 5,
    constellationId: 'constellation-0',
    studentTitle: '경계선의 탐사선',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-EXP-VAR-02'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '경계 반례 관찰과 <= 판정' },
  },
  {
    problemId: 'AC-EXP-LOOP-06',
    catalogOrder: 6,
    constellationId: 'constellation-0',
    studentTitle: '네 번 반복한 신호',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-EXP-VAR-02'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'for 반복에 따른 상태 변화 추적' },
  },
  {
    problemId: 'AC-EXP-WHILE-07',
    catalogOrder: 7,
    constellationId: 'constellation-0',
    studentTitle: '멈출 줄 아는 로버',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-EXP-LOOP-06', 'AC-EXP-BOUND-05'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'while 종료 조건과 상태 갱신' },
  },
  {
    problemId: 'AC-CODE-FIRST-ERROR-01',
    catalogOrder: 8,
    constellationId: 'constellation-0',
    studentTitle: '오류가 시작된 한 순간',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    entrySupport: 'embedded-foundation',
    prerequisites: ['AC-EXP-SEQ-01'],
    lensId: 'source-debug-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '코드 심판 및 최초 오류 위치 추적' },
  },
  {
    problemId: 'AC-EXP-EQUIV-09',
    catalogOrder: 9,
    constellationId: 'constellation-0',
    studentTitle: '두 코드, 같은 항로?',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-EXP-STEP-03', 'AC-EXP-BOUND-05', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '블랙박스 입출력 동치성 판단' },
  },
  {
    problemId: 'AC-EXP-REVERSE-10',
    catalogOrder: 10,
    constellationId: 'constellation-0',
    studentTitle: '숨은 로봇의 규칙',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-EXP-VAR-02', 'AC-EXP-STEP-03'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'Bebras', adaptationNotes: '블랙박스 규칙 역공학' },
  },

  // ==========================================
  // 성단 1. 조건과 상태 (Constellation 1) — 11~20
  // ==========================================
  {
    problemId: 'AC-COND-001',
    catalogOrder: 11,
    constellationId: 'constellation-1',
    studentTitle: '두 개의 안전 스위치',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-EXP-SEQ-01'],
    lensId: 'condition-table',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'and 조건 판단' },
  },
  {
    problemId: 'AC-COND-002',
    catalogOrder: 12,
    constellationId: 'constellation-1',
    studentTitle: '우주 구명정 승선 규칙',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-001'],
    lensId: 'condition-table',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'or 대안 조건 판단' },
  },
  {
    problemId: 'AC-COND-NOT-13',
    catalogOrder: 13,
    constellationId: 'constellation-1',
    studentTitle: '반전된 경보등',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-001'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'not 논리 부정' },
  },
  {
    problemId: 'AC-COND-ELIF-14',
    catalogOrder: 14,
    constellationId: 'constellation-1',
    studentTitle: '세 단계 위험 신호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-001', 'AC-EXP-BOUND-05'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: 'if/elif/else 3단계 분기' },
  },
  {
    problemId: 'AC-COND-RANGE-15',
    catalogOrder: 15,
    constellationId: 'constellation-1',
    studentTitle: '안전 온도 구간',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-COND-002', 'AC-COND-ELIF-14'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '수학 부등식과 구간 판정' },
  },
  {
    problemId: 'AC-COND-CLAMP-16',
    catalogOrder: 16,
    constellationId: 'constellation-1',
    studentTitle: '최대 출력 제한기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-RANGE-15'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '상한 제한 사고' },
  },
  {
    problemId: 'AC-COND-GRADE-17',
    catalogOrder: 17,
    constellationId: 'constellation-1',
    studentTitle: '탐사 등급 분류기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-ELIF-14'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '순서 있는 다중 조건 분기' },
  },
  {
    problemId: 'AC-COND-COMPLEX-18',
    catalogOrder: 18,
    constellationId: 'constellation-1',
    studentTitle: '문을 열지 말지 심판하라',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-COND-002', 'AC-COND-NOT-13'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'Bebras', adaptationNotes: '복합 논리식 분해' },
  },
  {
    problemId: 'AC-COND-TOGGLE-19',
    catalogOrder: 19,
    constellationId: 'constellation-1',
    studentTitle: '꺼졌다 켜지는 기지',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: [
      'AC-EXP-LOOP-06',
      'AC-CODE-FIRST-ERROR-01',
      'AC-COND-NOT-13',
    ],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'Boolean 토글 상태 추적' },
  },
  {
    problemId: 'AC-COND-ORDER-20',
    catalogOrder: 20,
    constellationId: 'constellation-1',
    studentTitle: '조건의 순서가 바꾸는 결과',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-COND-GRADE-17'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '분기 평가 우선순위 반례' },
  },

  // ==========================================
  // 성단 2. 수학 패턴 (Constellation 2) — 21~30
  // ==========================================
  {
    problemId: 'AC-PAT-003',
    catalogOrder: 21,
    constellationId: 'constellation-2',
    studentTitle: '얼어붙은 신호 다리',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-COND-001'],
    lensId: 'pattern-timeline',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '주기와 나머지 %' },
  },
  {
    problemId: 'AC-PAT-004',
    catalogOrder: 22,
    constellationId: 'constellation-2',
    studentTitle: '회전하는 우주 등대',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-PAT-003', 'AC-EXP-BOUND-05'],
    lensId: 'pattern-timeline',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '주기 안의 발광 구간' },
  },
  {
    problemId: 'AC-PAT-EVEN-23',
    catalogOrder: 23,
    constellationId: 'constellation-2',
    studentTitle: '홀수·짝수 비콘',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-PAT-003'],
    lensId: 'pattern-timeline',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '% 2 홀짝 판별' },
  },
  {
    problemId: 'AC-PAT-DIGIT-24',
    catalogOrder: 24,
    constellationId: 'constellation-2',
    studentTitle: '숫자 유성의 자릿수 신호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-PAT-003', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '10진법 자릿수 분해' },
  },
  {
    problemId: 'AC-PAT-REVNUM-25',
    catalogOrder: 25,
    constellationId: 'constellation-2',
    studentTitle: '뒤집힌 우주 번호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-PAT-DIGIT-24', 'AC-EXP-WHILE-07'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '자릿수 누적과 나눗셈' },
  },
  {
    problemId: 'AC-PAT-DIVISOR-26',
    catalogOrder: 26,
    constellationId: 'constellation-2',
    studentTitle: '운석의 약수 센서',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-PAT-003', 'AC-EXP-LOOP-06', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '작은 범위 약수 탐색' },
  },
  {
    problemId: 'AC-PAT-PRIME-27',
    catalogOrder: 27,
    constellationId: 'constellation-2',
    studentTitle: '소수 탐사 순찰대',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-PAT-DIVISOR-26', 'AC-EXP-BOUND-05'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '소수 판별 기본' },
  },
  {
    problemId: 'AC-PAT-GCD-28',
    catalogOrder: 28,
    constellationId: 'constellation-2',
    studentTitle: '두 톱니바퀴의 공통 박자',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: [
      'AC-PAT-DIVISOR-26',
      'AC-EXP-WHILE-07',
      'AC-PAT-DIGIT-24',
      'AC-EXP-SWAP-04',
    ],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'CSUnplugged', adaptationNotes: '반복 감산과 최대공약수' },
  },
  {
    problemId: 'AC-PAT-CALENDAR-29',
    catalogOrder: 29,
    constellationId: 'constellation-2',
    studentTitle: '다음 우주 캘린더',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-PAT-003'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '큰 수 주기 전이' },
  },
  {
    problemId: 'AC-PAT-PRIME-REV-30',
    catalogOrder: 30,
    constellationId: 'constellation-2',
    studentTitle: '잘못 만든 소수 판별기',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-PAT-PRIME-27', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '1과 경계값 오개념 반례' },
  },

  // ==========================================
  // 성단 3. 수열과 문자열 (Constellation 3) — 31~40
  // ==========================================
  {
    problemId: 'AC-SEQ-005',
    catalogOrder: 31,
    constellationId: 'constellation-3',
    studentTitle: '에너지 캡슐 선별 수거',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: [
      'AC-CODE-FIRST-ERROR-01',
      'AC-EXP-LOOP-06',
      'AC-COND-ELIF-14',
    ],
    lensId: 'sequence-accumulator',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'filter와 누적합' },
  },
  {
    problemId: 'AC-SEQ-MINMAX-32',
    catalogOrder: 32,
    constellationId: 'constellation-3',
    studentTitle: '가장 약한 신호와 강한 신호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-005', 'AC-EXP-BOUND-05'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '단일 순회 min/max' },
  },
  {
    problemId: 'AC-SEQ-COUNT-33',
    catalogOrder: 33,
    constellationId: 'constellation-3',
    studentTitle: '정상 캡슐은 몇 개?',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-005', 'AC-COND-RANGE-15'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '조건 부합 카운팅' },
  },
  {
    problemId: 'AC-SEQ-ADJACENT-34',
    catalogOrder: 34,
    constellationId: 'constellation-3',
    studentTitle: '어제보다 세진 신호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-MINMAX-32', 'AC-EXP-SWAP-04'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'USACO', adaptationNotes: '인접 원소 비교 시뮬레이션' },
  },
  {
    problemId: 'AC-SEQ-RUNNING-35',
    catalogOrder: 35,
    constellationId: 'constellation-3',
    studentTitle: '항해 일지의 누적 에너지',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '진행 누적합 리스트 생성' },
  },
  {
    problemId: 'AC-STR-REVERSE-01',
    catalogOrder: 36,
    constellationId: 'constellation-3',
    studentTitle: '뒤집힌 구조 메시지',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    entrySupport: 'embedded-foundation',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '문자열 역순 순회' },
  },
  {
    problemId: 'AC-STR-PALIN-37',
    catalogOrder: 37,
    constellationId: 'constellation-3',
    studentTitle: '거울 통신',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-STR-REVERSE-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '회문(Palindrome) 판별' },
  },
  {
    problemId: 'AC-SEQ-ROTATE-38',
    catalogOrder: 38,
    constellationId: 'constellation-3',
    studentTitle: '화물 한 칸씩 밀기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-RUNNING-35', 'AC-STR-REVERSE-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '배열 회전 시뮬레이션' },
  },
  {
    problemId: 'AC-STR-COMPRESS-39',
    catalogOrder: 39,
    constellationId: 'constellation-3',
    studentTitle: '반복 신호 압축기',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: [
      'AC-SEQ-ADJACENT-34',
      'AC-SEQ-RUNNING-35',
      'AC-STR-REVERSE-01',
    ],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'Bebras', adaptationNotes: 'Run-length 연속 압축' },
  },
  {
    problemId: 'AC-STR-PATTERN-40',
    catalogOrder: 40,
    constellationId: 'constellation-3',
    studentTitle: 'IOI 구조 신호 찾기',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: [
      'AC-SEQ-COUNT-33',
      'AC-SEQ-RUNNING-35',
      'AC-STR-REVERSE-01',
    ],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '부분 문자열 패턴 매칭' },
  },

  // ==========================================
  // 성단 4. 집합과 기록표 (Constellation 4) — 41~50
  // ==========================================
  {
    problemId: 'AC-SET-UNIQUE-01',
    catalogOrder: 41,
    constellationId: 'constellation-4',
    studentTitle: '서로 다른 광물은 몇 종?',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    entrySupport: 'embedded-foundation',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'set 중복 제거' },
  },
  {
    problemId: 'AC-SET-MEMBERSHIP-42',
    catalogOrder: 42,
    constellationId: 'constellation-4',
    studentTitle: '승선 명단 확인',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SET-UNIQUE-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'in 포함 여부' },
  },
  {
    problemId: 'AC-SET-INTERSECT-43',
    catalogOrder: 43,
    constellationId: 'constellation-4',
    studentTitle: '두 기지가 공통으로 가진 부품',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SET-MEMBERSHIP-42'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '교집합 직관' },
  },
  {
    problemId: 'AC-DICT-FREQ-44',
    catalogOrder: 44,
    constellationId: 'constellation-4',
    studentTitle: '신호 빈도표',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-SET-MEMBERSHIP-42'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: 'dict 카운터' },
  },
  {
    problemId: 'AC-DICT-MODE-45',
    catalogOrder: 45,
    constellationId: 'constellation-4',
    studentTitle: '가장 많이 온 신호',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-DICT-FREQ-44'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '최빈값 argmax' },
  },
  {
    problemId: 'AC-DICT-STOCK-46',
    catalogOrder: 46,
    constellationId: 'constellation-4',
    studentTitle: '화물 재고 장부',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-DICT-FREQ-44'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'dict 갱신과 조회' },
  },
  {
    problemId: 'AC-DICT-TWOSUM-47',
    catalogOrder: 47,
    constellationId: 'constellation-4',
    studentTitle: '목표 에너지의 두 캡슐',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-DICT-STOCK-46', 'AC-STR-REVERSE-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '필요한 짝을 계산하고 뒤쪽 구간에서 반복 확인' },
  },
  {
    problemId: 'AC-DICT-ONESHOT-48',
    catalogOrder: 48,
    constellationId: 'constellation-4',
    studentTitle: '한 번만 확인하는 에너지 탐지기',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-DICT-TWOSUM-47', 'AC-SET-INTERSECT-43'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: 'Set에 지나온 값을 기억하는 단일 순회 전략' },
  },
  {
    problemId: 'AC-DICT-ANAGRAM-49',
    catalogOrder: 49,
    constellationId: 'constellation-4',
    studentTitle: '같은 문자로 된 통신 패킷',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-DICT-FREQ-44'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '두 빈도표의 구조적 동치 비교' },
  },
  {
    problemId: 'AC-DICT-BUG-50',
    catalogOrder: 50,
    constellationId: 'constellation-4',
    studentTitle: '빈도표 오류 찾기',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-DICT-FREQ-44', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '최초 상태 차이로 초기화·갱신 오류 수리' },
  },

  // ==========================================
  // 성단 5. 시뮬레이션과 탐색 (Constellation 5) — 51~60
  // ==========================================
  {
    problemId: 'AC-SIM-ROVER-51',
    catalogOrder: 51,
    constellationId: 'constellation-5',
    studentTitle: '로버의 방향 명령',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-SEQ-005', 'AC-PAT-003', 'AC-COND-ELIF-14'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '위치 및 방향 상태' },
  },
  {
    problemId: 'AC-SIM-COMPASS-52',
    catalogOrder: 52,
    constellationId: 'constellation-5',
    studentTitle: '네 방향 우주 나침반',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SIM-ROVER-51', 'AC-PAT-003'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '방향 회전 순환' },
  },
  {
    problemId: 'AC-SIM-CLOCK-53',
    catalogOrder: 53,
    constellationId: 'constellation-5',
    studentTitle: '우주 시계 맞추기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SIM-COMPASS-52', 'AC-PAT-DIGIT-24'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '시계 연산과 올림' },
  },
  {
    problemId: 'AC-SIM-SWITCH-54',
    catalogOrder: 54,
    constellationId: 'constellation-5',
    studentTitle: '꺼졌다 켜지는 행성 스위치',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-SEQ-005', 'AC-COND-NOT-13'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '다중 스위치 상태 반전' },
  },
  {
    problemId: 'AC-SIM-BELT-55',
    catalogOrder: 55,
    constellationId: 'constellation-5',
    studentTitle: '화물 벨트 한 칸 이동',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-ROTATE-38'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '컨베이어 벨트 시뮬레이션' },
  },
  {
    problemId: 'AC-SORT-MIN-01',
    catalogOrder: 56,
    constellationId: 'constellation-5',
    studentTitle: '가장 작은 화물을 앞으로',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    entrySupport: 'embedded-foundation',
    prerequisites: ['AC-SEQ-MINMAX-32', 'AC-EXP-SWAP-04'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '선택 정렬 최소값 탐색' },
  },
  {
    problemId: 'AC-SORT-BUBBLE-57',
    catalogOrder: 57,
    constellationId: 'constellation-5',
    studentTitle: '큰 화물을 뒤로 밀기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SORT-MIN-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'CSUnplugged', adaptationNotes: '버블 정렬 인접 교환' },
  },
  {
    problemId: 'AC-SRCH-LINEAR-58',
    catalogOrder: 58,
    constellationId: 'constellation-5',
    studentTitle: '정렬되지 않은 창고 탐색',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-SEQ-005', 'AC-PAT-003'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '선형 탐색' },
  },
  {
    problemId: 'AC-SRCH-BINARY-59',
    catalogOrder: 59,
    constellationId: 'constellation-5',
    studentTitle: '절반씩 줄이는 숫자 행성',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-SRCH-LINEAR-58', 'AC-EXP-WHILE-07', 'AC-PAT-DIGIT-24'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'CSUnplugged', adaptationNotes: '이진 탐색 절반 줄이기' },
  },
  {
    problemId: 'AC-SRCH-PREFIX-60',
    catalogOrder: 60,
    constellationId: 'constellation-5',
    studentTitle: '여러 구간의 방사선 합',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-SEQ-RUNNING-35', 'AC-EXP-BOUND-05'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'USACO', adaptationNotes: '구간합 질의' },
  },

  // ==========================================
  // 성단 6. 가능성 연구소 (Constellation 6) — 61~70
  // ==========================================
  {
    problemId: 'AC-ENUM-PAIR-01',
    catalogOrder: 61,
    constellationId: 'constellation-6',
    studentTitle: '두 탐사 지점 모두 비교하기',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    entrySupport: 'embedded-foundation',
    prerequisites: ['AC-SEQ-005', 'AC-EXP-LOOP-06'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '이중 루프 쌍 탐색' },
  },
  {
    problemId: 'AC-ENUM-TARGET-62',
    catalogOrder: 62,
    constellationId: 'constellation-6',
    studentTitle: '목표 합을 만드는 두 캡슐',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-PAIR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '완전탐색 Two Sum' },
  },
  {
    problemId: 'AC-ENUM-TRIPLE-63',
    catalogOrder: 63,
    constellationId: 'constellation-6',
    studentTitle: '세 캡슐의 정확한 에너지',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-TARGET-62'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '삼중 루프 완전탐색' },
  },
  {
    problemId: 'AC-ENUM-COMB-64',
    catalogOrder: 64,
    constellationId: 'constellation-6',
    studentTitle: '센서 두 개 고르기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-PAIR-01', 'AC-SEQ-RUNNING-35'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '2개 조합 열거' },
  },
  {
    problemId: 'AC-ENUM-SUBSET-65',
    catalogOrder: 65,
    constellationId: 'constellation-6',
    studentTitle: '작은 장비 조합 보기',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-ENUM-COMB-64', 'AC-PAT-DIGIT-24'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'Bebras', adaptationNotes: '부분집합 트리' },
  },
  {
    problemId: 'AC-ENUM-KEYPAD-66',
    catalogOrder: 66,
    constellationId: 'constellation-6',
    studentTitle: '통신 키패드 문자 조합',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-SUBSET-65', 'AC-STR-COMPRESS-39'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '선택 트리 전이' },
  },
  {
    problemId: 'AC-ENUM-FILTER-67',
    catalogOrder: 67,
    constellationId: 'constellation-6',
    studentTitle: '시간 안에 할 수 있는 임무 조합',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-SUBSET-65', 'AC-COND-RANGE-15'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '조건 부합 조합 선별' },
  },
  {
    problemId: 'AC-ENUM-BEST-68',
    catalogOrder: 68,
    constellationId: 'constellation-6',
    studentTitle: '한도 안의 최고 장비 세트',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-ENUM-FILTER-67', 'AC-SEQ-MINMAX-32'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'USACO', adaptationNotes: '조합 열거 중 최댓값' },
  },
  {
    problemId: 'AC-ENUM-PRUNE-69',
    catalogOrder: 69,
    constellationId: 'constellation-6',
    studentTitle: '중복 탐색을 줄여라',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-ENUM-BEST-68', 'AC-SRCH-BINARY-59'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '가지치기(Pruning) 직관' },
  },
  {
    problemId: 'AC-ENUM-LOCK-70',
    catalogOrder: 70,
    constellationId: 'constellation-6',
    studentTitle: '두 자릿수 암호 추리',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-ENUM-PAIR-01', 'AC-PAT-DIGIT-24', 'AC-COND-COMPLEX-18'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'Bebras', adaptationNotes: '제약 조건 만족 탐색(2자리 재설계)' },
  },

  // ==========================================
  // 성단 7. 스택과 대기열 (Constellation 7) — 71~80
  // ==========================================
  {
    problemId: 'AC-STACK-BOX-71',
    catalogOrder: 71,
    constellationId: 'constellation-7',
    studentTitle: '우주복 박스 쌓기',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-SEQ-RUNNING-35', 'AC-EXP-WHILE-07'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'LIFO 스택 기본' },
  },
  {
    problemId: 'AC-STACK-PAREN-72',
    catalogOrder: 72,
    constellationId: 'constellation-7',
    studentTitle: '괄호 통신 검증',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-STACK-BOX-71'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '스택 괄호 매칭' },
  },
  {
    problemId: 'AC-STACK-UNDO-73',
    catalogOrder: 73,
    constellationId: 'constellation-7',
    studentTitle: '잘못된 명령 되돌리기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-STACK-BOX-71'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '실행 취소(Undo) 스택' },
  },
  {
    problemId: 'AC-NAV-005',
    catalogOrder: 74,
    constellationId: 'constellation-7',
    studentTitle: '구조 신호 대기열',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'fifo-queue',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'FIFO 대기열 처리' },
  },
  {
    problemId: 'AC-QUEUE-ROBOT-75',
    catalogOrder: 75,
    constellationId: 'constellation-7',
    studentTitle: '탐사 로봇 입장 순서',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-NAV-005'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'FIFO 순차 처리' },
  },
  {
    problemId: 'AC-QUEUE-ROBIN-76',
    catalogOrder: 76,
    constellationId: 'constellation-7',
    studentTitle: '번갈아 통신하는 기지',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-QUEUE-ROBOT-75'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '라운드로빈 큐 회전' },
  },
  {
    problemId: 'AC-QUEUE-CARD-77',
    catalogOrder: 77,
    constellationId: 'constellation-7',
    studentTitle: '한 장씩 버리는 우주 카드',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-QUEUE-ROBIN-76'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '카드2 큐 시뮬레이션' },
  },
  {
    problemId: 'AC-DEQUE-DOCK-78',
    catalogOrder: 78,
    constellationId: 'constellation-7',
    studentTitle: '앞·뒤 출입 우주 도크',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'published',
    prerequisites: ['AC-STACK-BOX-71', 'AC-QUEUE-ROBOT-75'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '양방향 덱 조작' },
  },
  {
    problemId: 'AC-STACK-QUEUE-79',
    catalogOrder: 79,
    constellationId: 'constellation-7',
    studentTitle: '스택 둘로 대기열 만들기',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-STACK-BOX-71', 'AC-QUEUE-ROBOT-75'],
    lensId: 'state-transition',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '스택 2개로 큐 구현' },
  },
  {
    problemId: 'AC-QUEUE-POP-80',
    catalogOrder: 80,
    constellationId: 'constellation-7',
    studentTitle: 'pop과 popleft의 한 줄 차이',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'published',
    prerequisites: ['AC-STACK-BOX-71', 'AC-NAV-005', 'AC-CODE-FIRST-ERROR-01'],
    lensId: 'state-transition',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'LIFO/FIFO 혼동 오개념 반례' },
  },

  // ==========================================
  // 성단 8. 격자 항해 (Constellation 8) — 81~90
  // ==========================================
  {
    problemId: 'AC-GRID-NEIGHBOR-81',
    catalogOrder: 81,
    constellationId: 'constellation-8',
    studentTitle: '격자의 이웃 신호',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'draft',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '2차원 4방향 이웃 탐색' },
  },
  {
    problemId: 'AC-GRID-BOUND-82',
    catalogOrder: 82,
    constellationId: 'constellation-8',
    studentTitle: '행성판의 가장자리',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-GRID-NEIGHBOR-81'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '2차원 격자 경계 체크' },
  },
  {
    problemId: 'AC-GRID-FLOOD-83',
    catalogOrder: 83,
    constellationId: 'constellation-8',
    studentTitle: '하나의 오염 구역 채우기',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'draft',
    prerequisites: ['AC-GRID-NEIGHBOR-81'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: 'Flood Fill 기본' },
  },
  {
    problemId: 'AC-GRID-ISLAND-84',
    catalogOrder: 84,
    constellationId: 'constellation-8',
    studentTitle: '떠 있는 기지의 개수',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-GRID-FLOOD-83'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '연결 요소 개수 세기' },
  },
  {
    problemId: 'AC-NAV-006',
    catalogOrder: 85,
    constellationId: 'constellation-8',
    studentTitle: '어둠 성운 구조 신호',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'published',
    prerequisites: ['AC-NAV-005'],
    lensId: 'grid-bfs',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '2D 격자 BFS 최단거리' },
  },
  {
    problemId: 'AC-GRID-MULTI-86',
    catalogOrder: 86,
    constellationId: 'constellation-8',
    studentTitle: '여러 기지에서 퍼지는 빛',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-NAV-006'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'USACO', adaptationNotes: '다중 시작점 BFS' },
  },
  {
    problemId: 'AC-GRAPH-ADJ-87',
    catalogOrder: 87,
    constellationId: 'constellation-8',
    studentTitle: '친구 기지 연결표',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-NAV-006'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '인접 리스트 그래프 표현' },
  },
  {
    problemId: 'AC-GRAPH-REACH-88',
    catalogOrder: 88,
    constellationId: 'constellation-8',
    studentTitle: '통신 가능한 기지 찾기',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-GRAPH-ADJ-87'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '도달 가능성 탐색' },
  },
  {
    problemId: 'AC-NAV-COMPARE-89',
    catalogOrder: 89,
    constellationId: 'constellation-8',
    studentTitle: 'BFS와 DFS가 다르게 보는 순서',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'draft',
    prerequisites: ['AC-NAV-006'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'BFS/DFS 탐색 순서 비교' },
  },
  {
    problemId: 'AC-NAV-VISITED-90',
    catalogOrder: 90,
    constellationId: 'constellation-8',
    studentTitle: 'visited를 너무 늦게 표시한 로봇',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'draft',
    prerequisites: ['AC-NAV-006'],
    lensId: 'source-debug-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: 'visited 갱신 시점 오개념' },
  },

  // ==========================================
  // 성단 9. 전략과 기억 (Constellation 9) — 91~100 (4 Capstones included)
  // ==========================================
  {
    problemId: 'AC-REC-BASE-91',
    catalogOrder: 91,
    constellationId: 'constellation-9',
    studentTitle: '작아지는 구조 문제',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'draft',
    prerequisites: ['AC-SEQ-005'],
    lensId: 'recursion-ladder-lens',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'JUNGOL', adaptationNotes: '재귀 기본과 종료 조건' },
  },
  {
    problemId: 'AC-REC-REPEAT-92',
    catalogOrder: 92,
    constellationId: 'constellation-9',
    studentTitle: '같은 계산을 또 했다',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-REC-BASE-91'],
    lensId: 'recursion-ladder-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '중복 부분문제 관찰' },
  },
  {
    problemId: 'AC-MEMO-CLIMB-01',
    catalogOrder: 93,
    constellationId: 'constellation-9',
    studentTitle: '계단을 오르는 방법',
    routeRole: 'core',
    learningRole: 'anchor',
    status: 'draft',
    prerequisites: ['AC-REC-REPEAT-92'],
    lensId: 'recursion-ladder-lens',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '1차원 메모이제이션 DP' },
  },
  {
    problemId: 'AC-GREEDY-INTERVAL-94',
    catalogOrder: 94,
    constellationId: 'constellation-9',
    studentTitle: '가장 많은 탐사 임무 선택',
    routeRole: 'core',
    learningRole: 'practice',
    status: 'draft',
    prerequisites: ['AC-SORT-MIN-01'],
    lensId: 'cycle-timeline',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'USACO', adaptationNotes: '활동 선택 그리디 직관' },
  },
  {
    problemId: 'AC-GREEDY-COIN-95',
    catalogOrder: 95,
    constellationId: 'constellation-9',
    studentTitle: '눈앞의 최선이 실패하는 동전',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'draft',
    prerequisites: ['AC-GREEDY-INTERVAL-94'],
    lensId: 'source-debug-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '그리디 반례 제시' },
  },
  {
    problemId: 'AC-DP-MAXSUB-96',
    catalogOrder: 96,
    constellationId: 'constellation-9',
    studentTitle: '연속 에너지 구간의 최고점',
    routeRole: 'branch',
    learningRole: 'review',
    status: 'draft',
    prerequisites: ['AC-MEMO-CLIMB-01'],
    lensId: 'sequence-accumulator',
    provenance: { sourceType: 'inspired', rightsStatus: 'reference-only', sourcePlatform: 'PAI', adaptationNotes: '연속 부분합 최대치' },
  },
  // 4 Capstone Projects
  {
    problemId: 'AC-CAP-DECODE-97',
    catalogOrder: 97,
    constellationId: 'constellation-9',
    studentTitle: '외계 언어 해독기 (캡스톤 1)',
    routeRole: 'capstone',
    learningRole: 'capstone',
    status: 'draft',
    prerequisites: ['AC-STR-REVERSE-01', 'AC-SET-UNIQUE-01'],
    lensId: 'string-scanner-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '문자열 + 딕셔너리 + 유효성 종합 캡스톤' },
  },
  {
    problemId: 'AC-CAP-DISPATCH-98',
    catalogOrder: 98,
    constellationId: 'constellation-9',
    studentTitle: '우주 화물 관제소 (캡스톤 2)',
    routeRole: 'capstone',
    learningRole: 'capstone',
    status: 'draft',
    prerequisites: ['AC-NAV-005', 'AC-SORT-MIN-01'],
    lensId: 'queue-conveyor-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '시뮬레이션 + 우선순위 대기열 캡스톤' },
  },
  {
    problemId: 'AC-CAP-RESCUE-99',
    catalogOrder: 99,
    constellationId: 'constellation-9',
    studentTitle: '구조 드론 지휘소 (캡스톤 3)',
    routeRole: 'capstone',
    learningRole: 'capstone',
    status: 'draft',
    prerequisites: ['AC-NAV-006'],
    lensId: 'grid-radar-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '격자 + BFS + 상태 관리 종합 캡스톤' },
  },
  {
    problemId: 'AC-CAP-AUTOROVER-100',
    catalogOrder: 100,
    constellationId: 'constellation-9',
    studentTitle: '자율 탐사 로버 (캡스톤 4)',
    routeRole: 'capstone',
    learningRole: 'capstone',
    status: 'draft',
    prerequisites: ['AC-MEMO-CLIMB-01', 'AC-NAV-006'],
    lensId: 'recursion-ladder-lens',
    provenance: { sourceType: 'original', rightsStatus: 'original', sourcePlatform: 'MetaSense', adaptationNotes: '전략 선택과 설명 중심 종합 캡스톤' },
  },
])

export function getEditorialEntryByProblemId(problemId) {
  return ALGORITHM_EDITORIAL_CATALOG.find((entry) => entry.problemId === problemId) || null
}

export function getEditorialEntryByCatalogOrder(order) {
  return ALGORITHM_EDITORIAL_CATALOG.find((entry) => entry.catalogOrder === order) || null
}

export function getPublishedEntries() {
  return ALGORITHM_EDITORIAL_CATALOG.filter((entry) => entry.status === 'published')
}
