import { useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import StudioInput from './StudioInput'
import ErrorCoach from './ErrorCoach'
import OutputLogs from './OutputLogs'
import PythonEditor from '../PythonWorld/PythonEditor'
import { readNotebook as notebookCells, editNativeCell as editNotebookCell, writeNotebook as joinNotebookCells } from './notebookFile.mjs'

export default function NotebookEditor({ uid, file, project, onChange, onRun, onRunAll, onReset, onExport, onImport, onExpand, liveIndex, surfaceSlotRef, inputRequest, onInputSubmitted, onStructureChange, outputs, running, activeIndex, onSelect }) {
  const cells = useMemo(() => notebookCells(file.text), [file.text])
  const [editingNote, setEditingNote] = useState(null)
  const replace = next => { onStructureChange(); onChange(joinNotebookCells(next)) }
  useEffect(() => {
    if (inputRequest) document.querySelector('.pgs-notebook .pgs-input-form')?.scrollIntoView({ block: 'nearest' })
  }, [inputRequest])
  const add = type => { replace([...cells, { type, source: '' }]); onSelect(cells.length); setEditingNote(type === 'markdown' ? cells.length : null) }
  const move = (i, step) => { const next = [...cells]; [next[i], next[i + step]] = [next[i + step], next[i]]; replace(next); onSelect(i + step) }
  return <div className="pgs-notebook">
    <div className="pgs-notebook-tools"><strong>노트북</strong><button disabled={running} onClick={onRunAll}>전체 실행</button><button onClick={onReset}>세션 초기화</button><button disabled={running} onClick={onImport}>.ipynb 가져오기</button><button title="코드와 설명을 저장합니다. 실행 출력은 포함하지 않습니다." onClick={onExport}>.ipynb 저장</button></div>
    <p className="pgs-notebook-hint">셀을 실행하면 변수와 객체가 다음 셀에 이어집니다. Shift+Enter로 실행하세요. 실행 결과와 입력창은 각 셀 아래에 나타납니다. 그림과 게임도 셀 안에서 조작하세요. 코드·설명은 자동 저장되며, 변수는 파일 전체 실행·세션 초기화·새로고침 시 초기화됩니다. 출력은 이 방문 중에만 보관됩니다.</p>
    {cells.map((cell, i) => { const result = outputs[i]; const stale = result && result.source !== cell.source
      return <section className={`pgs-cell${activeIndex === i ? ' pgs-cell-selected' : ''}`} key={i} aria-label={`${i + 1}번 ${cell.type === 'code' ? '코드' : '설명'} 셀`} onFocusCapture={() => onSelect(i)} onKeyDownCapture={event => { if (cell.type === 'code' && event.key === 'Enter' && event.shiftKey) { event.preventDefault(); event.stopPropagation(); if (!running) onRun(i) } }}>
        <div className="pgs-cell-header"><span>{cell.type === 'code' ? `[${result?.running ? '*' : result?.count ?? ' '}]` : '설명'} {i + 1}</span><div>{cell.type === 'code' ? <button disabled={running} aria-label={`${i + 1}번 셀 실행`} onClick={() => onRun(i)}>▶ 셀 실행</button> : <button onClick={() => setEditingNote(editingNote === i ? null : i)}>{editingNote === i ? '설명 보기' : '설명 편집'}</button>}<button disabled={running || i === 0} aria-label={`${i + 1}번 셀 위로`} onClick={() => move(i, -1)}>↑</button><button disabled={running || i === cells.length - 1} aria-label={`${i + 1}번 셀 아래로`} onClick={() => move(i, 1)}>↓</button><button disabled={running || cells.length === 1} aria-label={`${i + 1}번 셀 삭제`} onClick={() => { replace(cells.filter((_, index) => index !== i)); onSelect(Math.max(0, i - 1)) }}>삭제</button></div></div>
        {cell.type === 'code' ? <PythonEditor value={cell.source} onChange={text => onChange(editNotebookCell(file.text, i, text))} readOnly={running} colorful completionContext={{ files: project.files, path: file.path, prefix: cells.slice(0, i).filter(c => c.type === 'code').map(c => c.source).join('\n') + '\n' }} /> : editingNote === i ? <textarea aria-label={`${i + 1}번 설명 편집`} value={cell.source} onChange={e => onChange(editNotebookCell(file.text, i, e.target.value))} /> : <div className="pgs-cell-markdown" onDoubleClick={() => setEditingNote(i)}><ReactMarkdown>{cell.source || '설명 편집을 눌러 학습 내용을 적어 보세요.'}</ReactMarkdown></div>}
        {result && <div className="pgs-cell-output" aria-label={`${i + 1}번 셀 결과`}>{result.running && <small role="status">실행 중…</small>}{stale && <small>코드가 바뀌었습니다. 다시 실행하면 결과가 갱신됩니다.</small>}<OutputLogs key={result.request} logs={result.logs} />{result.logs?.filter(log => log.type === 'ERROR' && log.coach).slice(-1).map((log, j) => <ErrorCoach key={`${result.request}:${j}`} uid={uid} learningKey={log.coach.runId} learningScope={log.coach.scope} learningPath={log.coach.path} source={log.coach.source} currentSource={log.coach.path === file.path ? cell.source : project.files.find(f => f.path === log.coach.path)?.text} text={log.text} mode="notebook" />)}{result.displays?.map((display, j) => display.kind === 'table' ? <div className="pgs-cell-table" key={j}><table><thead><tr><th></th>{display.columns.map((v, k) => <th key={k}>{v}</th>)}</tr></thead><tbody>{display.rows.map((row, r) => <tr key={r}>{row.map((v, k) => <td key={k}>{v}</td>)}</tr>)}</tbody></table><small>{display.summary}</small></div> : <pre key={j}>{display.text}</pre>)}{liveIndex !== i && result.images?.map((image, j) => <img key={j} alt={`${i + 1}번 셀 그림 ${j + 1}`} src={`data:${image.mime};base64,${image.data}`} />)}{liveIndex === i && <><div className="pgs-cell-surface-tools"><span>실행 화면 · 마우스와 키보드로 조작할 수 있어요</span><button onClick={onExpand}>크게 보기</button></div><div className="pgs-cell-surface-slot" ref={surfaceSlotRef} aria-label={`${i + 1}번 셀 실행 화면`} /></>}{inputRequest?.notebook?.index === i && <StudioInput key={inputRequest.requestId} request={inputRequest} onSubmitted={onInputSubmitted} />}{result.truncated && <small>그림이 커서 저장된 미리보기 일부가 생략되었습니다. 셀을 다시 실행하면 전체 결과를 볼 수 있습니다.</small>}{result.surface && liveIndex !== i && !result.images?.length && <small>이 셀의 대화형 화면을 다시 보려면 셀을 실행하세요.</small>}{result.finished && !result.surface && liveIndex !== i && !result.logs?.length && !result.displays?.length && !result.images?.length && <small>실행 완료 · 출력 없음</small>}</div>}
      </section>
    })}
    <div className="pgs-notebook-add"><button disabled={running || cells.length >= 100} onClick={() => add('code')}>+ 코드 셀</button><button disabled={running || cells.length >= 100} onClick={() => add('markdown')}>+ 설명 셀</button></div>
  </div>
}
